/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 15a1d3e3911d1f8a15b47c0ac9e00f50)
interface __BaseEnv_Env {
	AI: Ai;
	HBX_API_BASE_URL: "https://api.test.hotelbeds.com";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "HBX_API_BASE_URL">> {}
}
