/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: d535e16383359677ba3d47b8ba28eebb)
interface __BaseEnv_Env {
	PROPOSALS_DB: D1Database;
	HBX_API_BASE_URL: "https://api.test.hotelbeds.com";
	PROPOSAL_ORIGIN: "https://proposal.waytoasia.com";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "HBX_API_BASE_URL" | "PROPOSAL_ORIGIN">> {}
}
