import {test,expect} from '@playwright/test';
test('financial workflow persists, drills down, exports and fits mobile',async({page})=>{
 test.skip(!test.info().config.configFile?.endsWith('playwright.finance.config.ts'),'Uses the isolated synthetic dashboard server.');
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 await page.goto('/preview-login');await page.getByRole('button',{name:'Finances',exact:true}).click();await page.getByRole('button',{name:'Open realistic demo'}).click();
 await expect(page.getByRole('heading',{name:'Financial overview',exact:true})).toBeVisible();
 const id=new URL(page.url()).hash.slice(9),response=await page.request.get('/dashboard/api/finance/'+id),before=await response.json();
 await expect(page.locator('[data-drill=earnings]')).toContainText((before.actual.earnings/100).toLocaleString('en-GB',{minimumFractionDigits:2}));
 await page.locator('[data-category=Hotels]').click();await expect(page.locator('#finance-items tbody tr')).toHaveCount(1);
 await page.getByRole('button',{name:'8 nights · two family rooms',exact:true}).click();await expect(page.locator('#finance-dialog [type=submit]')).toBeDisabled();
 const field=page.locator('[name=actual_otherCost]'),original=await field.inputValue();await field.fill('24.00');await page.locator('#finance-dialog [type=submit]').click();await expect(page.locator('#notice')).toHaveText('✓ Financial changes saved.');
 await page.reload();await expect(page.getByRole('heading',{name:'Financial overview',exact:true})).toBeVisible();await page.getByRole('button',{name:'8 nights · two family rooms',exact:true}).click();await expect(page.locator('[name=actual_otherCost]')).toHaveValue('24.00');await page.locator('[name=actual_otherCost]').fill(original);await page.locator('#finance-dialog [type=submit]').click();
 await page.getByRole('button',{name:'Record entry',exact:true}).click();await page.getByLabel('Entry type').selectOption('receipt');await page.getByLabel('Amount',{exact:true}).fill('12.50');await page.getByLabel('Reference',{exact:true}).fill('E2E TEST PAYMENT');await page.locator('#finance-dialog [type=submit]').click();await expect(page.locator('#finance-payments')).toContainText('E2E TEST PAYMENT');
 await page.locator('#finance-payments tr').filter({hasText:'E2E TEST PAYMENT'}).filter({has:page.getByRole('button',{name:'Void',exact:true})}).last().getByRole('button',{name:'Void',exact:true}).click();await page.getByLabel('Reason').fill('Synthetic test reversal');await page.locator('#finance-dialog [type=submit]').click();
 await page.getByRole('button',{name:'Quoted / expected',exact:true}).click();await expect(page.locator('[data-basis=quote]')).toHaveAttribute('aria-pressed','true');
 const downloadPromise=page.waitForEvent('download');await page.getByRole('link',{name:'Export CSV'}).click();const download=await downloadPromise;expect(download.suggestedFilename()).toContain('internal-finance-quote.csv');
 await page.getByRole('link',{name:'Back to enquiry',exact:true}).click();
 await expect(page.getByRole('tab',{name:'Trip overview',exact:true})).toHaveAttribute('aria-selected','true');
 await expect(page.locator('#enquiry-finances')).toBeHidden();
 await page.getByRole('tab',{name:'Finance',exact:true}).click();
 await expect(page.getByRole('heading',{name:'This file’s finances',exact:true})).toBeVisible();
 await expect(page.locator('#enquiry-finances .finance-kpi')).toHaveCount(5);
 await page.getByText('Individual item earnings (7)',{exact:true}).click();
 await expect(page.locator('#enquiry-finances .enquiry-finance-items tbody tr')).toHaveCount(7);
 await page.getByRole('button',{name:'8 nights · two family rooms',exact:true}).click();
 await page.getByLabel('Internal notes').fill('Synthetic example. Inline enquiry edit verification '+Date.now());
 await page.locator('#finance-dialog [type=submit]').click();
 await expect(page.locator('#enquiry-finances [data-inline-feedback]')).toHaveText('✓ Financial changes saved.');
 await expect(page.locator('#detail-view')).toBeVisible();
 await expect(page.locator('#secondary-view')).toBeHidden();
 await page.locator('#enquiry-finances summary').click();
 await page.screenshot({path:'/tmp/waytoasia-enquiry-finance.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.setViewportSize({width:1280,height:900});
 await page.getByRole('link',{name:'Full financial workspace ↗'}).click();
 await expect(page.getByRole('heading',{name:'Financial overview',exact:true})).toBeVisible();
 await page.screenshot({path:'/tmp/waytoasia-finance-desktop.png',fullPage:true});
 await page.emulateMedia({media:'print'});await page.pdf({path:'/tmp/waytoasia-finance-internal.pdf',format:'A4',landscape:true,printBackground:true});await page.emulateMedia({media:'screen'});
 await page.setViewportSize({width:390,height:844});await page.reload();await expect(page.getByRole('heading',{name:'Financial overview',exact:true})).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:'/tmp/waytoasia-finance-mobile.png',fullPage:true});expect(errors).toEqual([]);
});
test('existing tour enquiry automatically shows its published DKK price and honest pending costs',async({page})=>{
 test.skip(!test.info().config.configFile?.endsWith('playwright.finance.config.ts'),'Uses the isolated synthetic dashboard server.');
 const {database}=await import('./dashboard/support');const {sqlite}=database('.wrangler/dashboard-preview.sqlite');
 const id=crypto.randomUUID(),now=new Date().toISOString(),e={id};
 sqlite.prepare('INSERT INTO clients VALUES (?,?,?,?,?)').run(id,`catalogue-${id}@example.invalid`,'Published tour price test','',now);
 sqlite.prepare('INSERT INTO enquiries (id,reference,client_id,source,requirements_json,original_message,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)').run(id,'TEST-'+id,id,'Synthetic test',JSON.stringify({title:'Mr',departureDate:'2026-12-07',tour:'silk-and-courtyards',adults:'2',children:'0',budgetCurrency:'DKK'}),'Synthetic price verification',now,now);sqlite.close();
 await page.goto('/preview-login');await page.goto('/dashboard#'+e.id);
 await expect(page.locator('#enquiry-finance-summary')).toContainText('98,400');
 await expect(page.getByRole('heading',{name:'Published tour programme'})).toBeVisible();
 await expect(page.locator('.quoted-trip h2')).toHaveText('Silk & Courtyards');
 await expect(page.locator('.trip-facts')).toContainText('2026-12-07');
 await page.getByRole('tab',{name:'Finance',exact:true}).click();
 await expect(page.locator('#enquiry-finances .finance-published')).toContainText('DKK 49,200.00');
 await expect(page.locator('#enquiry-finances .finance-kpi').first()).toContainText('DKK 98,400.00');
 await expect(page.locator('#enquiry-finances .featured')).toContainText('Not yet known');
 await page.getByText('Tour price & item earnings',{exact:true}).click();await expect(page.locator('#enquiry-finances .enquiry-finance-items tbody')).toContainText('Silk & Courtyards');
 await expect(page.locator('.finance-services')).toContainText('Included in package');
 await expect(page.locator('.finance-services')).toContainText('Flights');
 await page.screenshot({path:'/tmp/waytoasia-published-price.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.getByRole('link',{name:'Full financial workspace ↗'}).click();await expect(page.locator('[data-drill=revenue]')).toContainText('DKK 98,400.00');
 await page.setViewportSize({width:1280,height:900});
 await page.getByRole('button',{name:'Finances',exact:true}).click();
 await expect(page.locator('#portfolio-currency')).toHaveValue('');
 const row=page.locator('#portfolio-content tbody tr').filter({hasText:'TEST-'+id});
 await expect(row).toContainText('DKK 98,400.00');
 await expect(row).toContainText('Hotels');
 await expect(row).toContainText('Flights');
 await expect(row).toContainText('Not recorded');
 await page.screenshot({path:'/tmp/waytoasia-all-files.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});
test('enquiry opens on a clear selected trip with finance and communication in separate tabs',async({page})=>{
 test.skip(!test.info().config.configFile?.endsWith('playwright.finance.config.ts'),'Uses synthetic dashboard server.');
 await page.goto('/preview-login');const rows=await (await page.request.get('/dashboard/api/enquiries')).json(),id=rows.rows[0].id;
 const payload={suggestion:{title:'Bangkok and Chiang Mai',summary:'A relaxed cultural journey.',route:[{place:'Bangkok',onwardTravel:'Express bus to Chiang Mai'},{place:'Chiang Mai'}],hotelStays:[{place:'Bangkok',nights:3,options:[{id:'hotel-a',name:'Selected Bangkok Hotel',roomGuidance:'Deluxe twin room'}]}],dayPlans:[{day:1,place:'Bangkok',options:[{id:'activity-a',name:'Temple walk',description:'Guided visit to the temples.'}]}]},builderChoices:{hotels:{'stay-0':'hotel-a'},days:{'day-1':'activity-a'}}};
 await page.route('**/dashboard/api/enquiries/'+id,async route=>{const response=await route.fetch(),body=await response.json();body.proposals=[{id:'synthetic-proposal',version:1,title:'Bangkok and Chiang Mai',status:'Sent',url:'https://example.invalid/proposal',snapshot_json:JSON.stringify({payload}),created_at:new Date().toISOString()}];await route.fulfill({response,json:body})});
 await page.goto('/dashboard#'+id);await expect(page.locator('.quoted-trip')).toContainText('Selected Bangkok Hotel');await expect(page.locator('.quoted-trip')).toContainText('Temple walk');await expect(page.locator('.quoted-trip')).toContainText('Express bus to Chiang Mai');await expect(page.locator('#enquiry-finances')).toBeHidden();await expect(page.locator('#edit-form')).toBeVisible();
 const day=page.locator('details.trip-day').first();await expect(day).not.toHaveAttribute('open','');await expect(day.locator('.trip-day-content')).toBeHidden();await day.locator('summary').click();await expect(day.locator('.trip-day-content')).toBeVisible();await day.locator('summary').press('Enter');await expect(day.locator('.trip-day-content')).toBeHidden();
 await page.screenshot({path:'/tmp/waytoasia-trip-tabs.png',fullPage:true});
 await page.getByRole('tab',{name:'Communication',exact:true}).click();await expect(page.locator('#send-form')).toBeVisible();await expect(page.locator('#note-form')).toBeVisible();await expect(page.locator('.quoted-trip')).toBeHidden();
 await page.getByRole('tab',{name:'Trip overview',exact:true}).click();await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});

test('editing an unpriced amount persists without a separate checkbox step',async({page})=>{
 test.skip(!test.info().config.configFile?.endsWith('playwright.finance.config.ts'),'Uses isolated synthetic dashboard server.');
 await page.goto('/preview-login');await page.getByRole('button',{name:'Finances',exact:true}).click();await page.getByRole('button',{name:'Open realistic demo'}).click();
 await page.getByRole('button',{name:'Add item',exact:true}).click();
 const name='Synthetic amount persistence '+Date.now();
 await page.getByLabel('Description',{exact:true}).fill(name);
 await expect(page.locator('[name=actual_priced]')).not.toBeChecked();
 await page.locator('[name=actual_priceBase]').fill('125.50');
 await expect(page.locator('[name=actual_priced]')).toBeChecked();
 await expect(page.locator('[name=quote_priced]')).not.toBeChecked();
 await page.locator('#finance-dialog [type=submit]').click();
 await expect(page.locator('#notice')).toHaveText('✓ Financial changes saved.');
 await page.reload();await page.getByRole('button',{name,exact:true}).click();
 await expect(page.locator('[name=actual_priceBase]')).toHaveValue('125.50');
 await expect(page.locator('[name=actual_priced]')).toBeChecked();
 await expect(page.locator('[name=quote_priced]')).not.toBeChecked();
 await expect(page.locator('#finance-dialog [type=submit]')).toBeDisabled();
});
