import test from 'node:test';
import assert from 'node:assert/strict';
import {enrichHotelStays,hotelLocation,hotelPhoto,mapHotelRates} from '../functions/_lib/planner-hotels';
import {parseTripPlannerRequest} from '../src/lib/tripPlanner';
const profile=parseTripPlannerRequest({locale:'en',interests:['food'],destinations:['thailand'],travelStartDate:'2027-02-10',travelEndDate:'2027-02-17',adults:2,children:0,budget:'comfort'})!;
const payload={hotels:[{id:'one',name:'ASAI Bangkok Chinatown',address:'Bangkok',rating:9,main_photo:'https://static.cupid.travel/hotels/1.jpg'},{id:'two',name:'Second Bangkok Hotel',address:'Bangkok'}],data:['one','two'].map(hotelId=>({hotelId,roomTypes:[{rateType:'standard',offerRetailRate:{amount:270,currency:'EUR'},rates:[{name:'Twin room',boardName:'Room Only'}]}]}))};
test('maps distinct hotels and sample stay totals without exposing offers or credentials',()=>{const options=mapHotelRates(payload,profile,'2027-02-10','2027-02-13');assert.equal(options.length,2);assert.equal(options[0].supplierQuote?.mode,'sandbox');assert.equal(options[0].supplierQuote?.amount,270);assert.equal(options[0].imageUrl,'https://static.cupid.travel/hotels/1.jpg');assert.equal(mapHotelRates({...payload,data:[...payload.data,payload.data[0]]},profile,'a','b').length,2);});
test('rejects unsafe images and incomplete or wrong-currency rates',()=>{assert.equal(hotelPhoto('https://evil.example/image.jpg'),undefined);assert.equal(hotelPhoto('javascript:alert(1)'),undefined);assert.deepEqual(mapHotelRates({hotels:payload.hotels,data:[{hotelId:'one',roomTypes:[{rateType:'standard',offerRetailRate:{amount:270,currency:'USD'}}]}]},profile,'a','b'),[])});
test('uses known coordinates and does not guess composite or ambiguous locations',()=>{assert.equal(hotelLocation('China: Shaxi',[])?.latitude,26.320);assert.equal(hotelLocation('Hanoi & Ninh Binh',['vietnam']),null);assert.equal(hotelLocation('Unknown',[]),null)});
test('sandbox only, sequential stay dates and graceful provider fallback',async()=>{const stays=[{place:'Thailand: Bangkok',nights:3,options:[]},{place:'Thailand: Chiang Mai',nights:4,options:[]}];let calls=0;const fetcher:typeof fetch=async(_url,init)=>{calls++;const body=JSON.parse(String(init?.body));assert.equal(body.checkin,calls===1?'2027-02-10':'2027-02-13');return Response.json(payload)};assert.deepEqual(await enrichHotelStays('prod_no',profile,stays,fetcher),stays);assert.equal(calls,0);assert.equal((await enrichHotelStays('sand_test',profile,stays,fetcher))[0].options.length,2);const failed=await enrichHotelStays('sand_test',profile,stays,async()=>{throw Error('timeout')});assert.equal(failed[0].options.length,0);assert.match(failed[0].supplierNote!,/not available/);});
test('does not invent child ages',async()=>{const result=await enrichHotelStays('sand_test',{...profile,children:1},[{place:'Bangkok',nights:3,options:[]}],async()=>{throw Error('must not call')});assert.match(result[0].supplierNote!,/child ages/)});

test('hotel checkout never extends beyond the return date when AI overcounts nights',async()=>{let end='';const result=await enrichHotelStays('sand_test',profile,[{place:'Bangkok',nights:4,options:[]},{place:'Chiang Mai',nights:4,options:[]}],async(_url,init)=>{end=JSON.parse(String(init?.body)).checkout;return Response.json(payload)});assert.deepEqual(result.map(s=>s.nights),[4,3]);assert.equal(end,'2027-02-17')});
