import {test,expect} from '@playwright/test';
const locales=['en','es','it','fr','nl','hu','sv','da','no'];
for(const locale of locales)test(`${locale} homepage`,async({page})=>{const response=await page.goto(`/${locale}/`);expect(response?.ok()).toBeTruthy();await expect(page.locator('h1')).toBeVisible();await expect(page.locator('html')).toHaveAttribute('lang',locale)});
test('country and tour routes resolve',async({page})=>{for(const path of ['/en/japan','/da/thailand','/fr/vietnam/tours','/en/japan/tours/japan-in-stillness']){const response=await page.goto(path);expect(response?.status(),path).toBe(200);await expect(page.locator('h1')).toBeVisible()}});
test('language switcher preserves route',async({page})=>{await page.goto('/en/japan');await page.locator('[data-language]').selectOption('/fr/japan');await expect(page).toHaveURL(/\/fr\/japan\/?$/)});
test('journey discovery is usable',async({page})=>{await page.goto('/en/');await expect(page.getByRole('heading',{name:'What should your Asia feel like?'})).toBeVisible();await page.getByLabel('Where would you like to go?').selectOption('japan');await page.getByRole('button',{name:/See journey ideas/}).click();await expect(page).toHaveURL(/\/en\/tours\/?\?country=japan/)});
test('desktop destination navigation exposes the full collection',async({page})=>{await page.setViewportSize({width:1280,height:800});await page.goto('/en/');const toggle=page.locator('[data-nav-toggle]');await toggle.focus();await expect(page.getByRole('link',{name:/Japan/}).first()).toBeVisible();});
test('editorial hub and story routes resolve',async({page})=>{for(const path of ['/en/inspiration','/da/inspiration/when-to-travel-japan']){const response=await page.goto(path);expect(response?.status(),path).toBe(200);await expect(page.locator('h1')).toBeVisible()}});
test('journey detail presents a complete travel product',async({page})=>{await page.goto('/en/japan/tours/japan-in-stillness');await expect(page.getByRole('heading',{name:'Japan in Stillness'})).toBeVisible();await expect(page.getByText('Journey at a glance')).toBeVisible();await expect(page.getByRole('img',{name:'Journey route through Japan'})).toBeVisible();await expect(page.getByRole('heading',{name:'What the guide price covers.'})).toBeVisible();await expect(page.getByRole('heading',{name:/14 days, day by day/})).toBeVisible();await expect(page.locator('.daily')).toHaveCount(14);await expect(page.getByRole('heading',{name:'Character, comfort and a sense of place.'})).toBeVisible();await expect(page.getByRole('link',{name:/Request a proposal/})).toHaveAttribute('href',/contact\?tour=japan-in-stillness/)});
