import {test,expect} from '@playwright/test';
import {tours} from '../src/content/data';
import {getRouteModes} from '../src/content/routeTransport';
import translations from '../src/content/translations.generated.json' with {type:'json'};
const locales=['en','es','it','fr','nl','hu','sv','da','no'];
test('catalogue contains four distinct tours per country',()=>{for(const country of ['china','south-korea','thailand','vietnam','indonesia']){const countryTours=tours.filter(tour=>tour.country===country);expect(countryTours).toHaveLength(4);expect(new Set(countryTours.map(tour=>tour.slug)).size).toBe(4);expect(countryTours.every(tour=>tour.route&&tour.route.length>=3)).toBeTruthy()}});
test('every tour map has stop timing and explicit transport data',()=>{for(const tour of tours){expect(tour.route,`${tour.slug} route`).toBeDefined();expect(tour.itinerary.length,`${tour.slug} stop timing`).toBeGreaterThan(0);for(let index=0;index<tour.route!.length-1;index++)expect(getRouteModes(tour.route![index],tour.route![index+1]),`${tour.slug} leg ${index+1}`).not.toHaveLength(0)}});
test('every country landing page displays four readable journey decks',async({page})=>{for(const country of ['china','south-korea','thailand','vietnam','indonesia']){await page.goto(`/en/${country}`);const cards=page.locator('.journey-cards .card');await expect(cards).toHaveCount(4);await expect(page.locator('.journey-cards')).toBeVisible();await expect(cards.first().locator('h3')).toHaveCSS('color','rgb(22, 35, 29)')}});
test('tour collections use a three-column desktop grid',async({page})=>{await page.setViewportSize({width:1440,height:900});for(const path of ['/en/thailand','/en/thailand/tours','/en/tours']){await page.goto(path);const cards=page.locator(path==='/en/tours'?'.tour-grid .tour':'.cards .card');const boxes=await cards.evaluateAll(nodes=>nodes.slice(0,4).map(node=>({x:node.getBoundingClientRect().x,y:node.getBoundingClientRect().y})));expect(boxes).toHaveLength(4);expect(boxes[0].y).toBeCloseTo(boxes[1].y,0);expect(boxes[1].y).toBeCloseTo(boxes[2].y,0);expect(boxes[2].x).toBeGreaterThan(boxes[1].x);expect(boxes[3].y).toBeGreaterThan(boxes[0].y)}});
for(const locale of locales)test(`${locale} homepage`,async({page})=>{const response=await page.goto(`/${locale}/`);expect(response?.ok()).toBeTruthy();await expect(page.locator('h1')).toBeVisible();await expect(page.locator('html')).toHaveAttribute('lang',locale)});
test('country and tour routes resolve',async({page})=>{for(const path of ['/en/south-korea','/da/thailand','/fr/vietnam/tours','/en/south-korea/tours/seoul-and-ancient-kingdoms']){const response=await page.goto(path);expect(response?.status(),path).toBe(200);await expect(page.locator('h1')).toBeVisible()}});
test('every translated catalogue covers the complete English source set',()=>{const catalogs=translations as Record<string,Record<string,string>>;const english=Object.keys(catalogs.en);for(const locale of locales.slice(1)){expect(english.filter(source=>!catalogs[locale][source])).toEqual([])}});
test('translated pages keep stable localized routes and replace substantive copy',async({page})=>{for(const locale of locales.slice(1)){await page.goto(`/${locale}/`);await expect(page.locator(`a[href="/${locale}/tours"]`).first()).toBeAttached()}await page.goto('/da/south-korea/tours/seoul-and-ancient-kingdoms');await expect(page.locator('#overview')).toContainText(translations.da['Tour overview']);await expect(page.locator('#overview')).not.toContainText('Tour overview');await page.goto('/fr/about');await expect(page.locator('.team-head')).toContainText(translations.fr['Your trip starts with a person.']);await page.goto('/es/contact');await expect(page.locator('fieldset[data-step="3"] legend')).toContainText(translations.es['Review your enquiry'])});
test('language switcher preserves route',async({page})=>{await page.goto('/en/south-korea');await page.locator('[data-language]').selectOption('/fr/south-korea');await expect(page).toHaveURL(/\/fr\/south-korea\/?$/)});
test('journey discovery is usable',async({page})=>{await page.goto('/en/');await expect(page.getByRole('heading',{name:'What should your Asia feel like?'})).toBeVisible();await page.getByLabel('Where would you like to go?').selectOption('south-korea');await page.getByRole('button',{name:/See journey ideas/}).click();await expect(page).toHaveURL(/\/en\/tours\/?\?country=south-korea/)});
test('desktop destination navigation exposes the full collection',async({page})=>{await page.setViewportSize({width:1280,height:800});await page.goto('/en/');const toggle=page.locator('[data-nav-toggle]');await toggle.focus();await expect(page.getByRole('link',{name:/South Korea/}).first()).toBeVisible();});
test('editorial hub and story routes resolve',async({page})=>{for(const path of ['/en/inspiration','/da/inspiration/when-to-travel-south-korea']){const response=await page.goto(path);expect(response?.status(),path).toBe(200);await expect(page.locator('h1')).toBeVisible()}});
test('global header remains readable over bright hero photography',async({page})=>{await page.goto('/es/thailand');const header=page.locator('.header');await expect(header).toHaveCSS('color','rgb(243, 238, 223)');await expect(header).toHaveCSS('background-color','rgba(6, 25, 19, 0.84)');expect(await header.evaluate(node=>getComputedStyle(node).backgroundImage)).toContain('linear-gradient')});
test('about page introduces four personal travel designers',async({page})=>{await page.goto('/en/about');await expect(page.getByRole('heading',{name:'Your trip starts with a person.'})).toBeVisible();const cards=page.locator('.staff-card');await expect(cards).toHaveCount(4);await expect(cards.first().locator('img')).toBeVisible();await expect(cards.first()).toContainText('Demonstration profile');await expect(cards.first()).toContainText('Languages')});
test('about page explains the local support model',async({page})=>{await page.goto('/en/about');await expect(page.getByRole('heading',{name:'Close to you. Present in Asia.'})).toBeVisible();await expect(page.locator('.office-network li')).toHaveCount(5);await expect(page.locator('.values')).toContainText('Support where you travel');await expect(page.locator('.value-grid article')).toHaveCount(4)});
test('staff portraits use consistent framed crops',async({page})=>{await page.setViewportSize({width:1440,height:1000});await page.goto('/en/about');const portraits=page.locator('.staff-card img');await expect(portraits).toHaveCount(4);const frames=await portraits.evaluateAll(images=>images.map(image=>{const box=image.getBoundingClientRect();return{ratio:box.width/box.height,fit:getComputedStyle(image).objectFit,position:getComputedStyle(image).objectPosition}}));for(const frame of frames){expect(Math.abs(frame.ratio-.8)).toBeLessThan(.01);expect(frame.fit).toBe('cover');expect(frame.position).not.toBe('50% 50%')}});
test('proposal form captures traveller and trip requirements',async({page})=>{await page.goto('/en/contact?tour=seoul-and-ancient-kingdoms');await expect(page.getByRole('heading',{name:'Tell us who is travelling.'})).toBeVisible();await page.getByLabel('First name *').fill('Test');await page.getByLabel('Last name *').fill('Traveller');await page.getByLabel('Email address *').fill('test@example.com');await page.getByLabel('Phone number *').fill('+45 12345678');await page.getByLabel('Country of residence *').fill('Denmark');await page.getByLabel('Preferred contact *').selectOption('email');await page.getByRole('button',{name:/Continue to trip details/}).click();await expect(page.getByRole('group',{name:/Trip and travellers/})).toBeVisible();await expect(page.getByLabel('Journey idea')).toHaveValue('seoul-and-ancient-kingdoms');await expect(page.getByLabel('Destination *')).toHaveValue('south-korea');await expect(page.getByLabel('Budget per person *')).toBeVisible();await expect(page.getByLabel('Dietary, mobility or accessibility requirements')).toBeVisible()});
test('proposal trip fields share consistent row baselines',async({page})=>{await page.setViewportSize({width:1440,height:1100});await page.goto('/en/contact?tour=seoul-and-ancient-kingdoms');await page.getByLabel('First name *').fill('Test');await page.getByLabel('Last name *').fill('Traveller');await page.getByLabel('Email address *').fill('test@example.com');await page.getByLabel('Phone number *').fill('+45 12345678');await page.getByLabel('Country of residence *').fill('Denmark');await page.getByLabel('Preferred contact *').selectOption('email');await page.getByRole('button',{name:/Continue to trip details/}).click();for(const fields of [['departureDate','dateFlexibility','duration'],['budgetCurrency','budgetPerPerson','accommodation']]){const tops=await Promise.all(fields.map(name=>page.locator(`[name="${name}"]`).evaluate(element=>element.getBoundingClientRect().top)));expect(Math.max(...tops)-Math.min(...tops)).toBeLessThanOrEqual(1)}});
test('proposal review is grouped into readable summary cards',async({page})=>{await page.goto('/en/contact?tour=seoul-and-ancient-kingdoms');await page.getByLabel('First name *').fill('Test');await page.getByLabel('Last name *').fill('Traveller');await page.getByLabel('Email address *').fill('test@example.com');await page.getByLabel('Phone number *').fill('+45 12345678');await page.getByLabel('Country of residence *').fill('Denmark');await page.getByLabel('Preferred contact *').selectOption('email');await page.getByRole('button',{name:/Continue to trip details/}).click();await page.getByLabel('Earliest departure *').fill('2027-04-12');await page.getByLabel('Date flexibility *').selectOption('± 3 days');await page.getByLabel('Trip length *').selectOption('11–14 days');await page.getByLabel('Departure airport or city *').fill('Copenhagen');await page.getByLabel('Budget per person *').fill('40000');await page.getByLabel('Accommodation *').selectOption('Premium 4-star');await page.getByRole('button',{name:/Review enquiry/}).click();await expect(page.locator('.review-section')).toHaveCount(5);await expect(page.getByRole('heading',{name:'Your details'})).toBeVisible();await expect(page.getByRole('heading',{name:'Journey plan'})).toBeVisible();await expect(page.locator('[data-review]')).toContainText('Seoul & Ancient Kingdoms');await expect(page.locator('.consent')).toHaveCSS('display','flex');const checkboxHeight=await page.locator('.consent input').evaluate(element=>element.getBoundingClientRect().height);expect(checkboxHeight).toBeLessThan(24)});

test('company name stays Way to Asia in every translation',()=>{
  for(const [locale,entries] of Object.entries(translations)){
    for(const [source,translated] of Object.entries(entries)){
      if(source.includes('Way to Asia'))expect(translated.split('Way to Asia').length,`${locale}: ${source}`).toBe(source.split('Way to Asia').length);
    }
  }
});
test('company wordmarks, titles and copy are protected across all languages',async({page})=>{
  test.setTimeout(60000);
  for(const locale of locales){
    for(const path of ['', 'about','contact']){
      await page.goto(`/${locale}/${path}`);
      const brand=page.locator('header .brand');
      await expect(brand).toHaveAttribute('translate','no');
      await expect(brand).toHaveAccessibleName(/^Way to Asia /);
      expect((await brand.textContent())!.replace(/\s/g,'')).toBe('WAYtoASIA');
      await expect(page.locator('footer .mark')).toHaveText('WAY to ASIA');
      await expect(page.locator('footer .mark')).toHaveAttribute('translate','no');
      await expect(page).toHaveTitle(/Way to Asia/);
      await expect(page.locator('footer .bottom')).toContainText('Way to Asia');
      if(path==='about')await expect(page.locator('main')).toContainText('Way to Asia');
      if(path==='contact')await expect(page.locator('.consent')).toContainText('Way to Asia');
    }
  }
});
