import {liveFlightNote,flightTable} from './flight-display';
export interface FlightSegment {origin:string;destination:string;departure:string;arrival:string;airline:string;flightNumber:string;duration:string;connectionDuration?:string;originCity?:string;originName?:string;destinationCity?:string;destinationName?:string;cabin?:string;operatingAirline?:string;originTimeZone?:string;destinationTimeZone?:string;stops?:Array<{airport:string;city:string;name:string;arrival:string;departure:string;duration:string}>}
export interface FlightItinerary {source:'duffel-test'|'sample'|'serpapi-google-flights';offerId:string;retrievedAt:string;totalAmount?:string;totalCurrency?:string;slices:FlightSegment[][];transfers?:Array<{place:string;airport:string;airportName?:string}>}
export class FlightError extends Error {constructor(message:string,public status=400){super(message)}}
const record=(v:unknown):Record<string,unknown>=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{};
const text=(v:unknown)=>typeof v==='string'?v.slice(0,160):'';
export function normaliseOffer(value:unknown):FlightItinerary {
 const offer=record(value);if(offer.live_mode!==false)throw new FlightError('Only test flight offers are allowed.',502);
 const slices=(Array.isArray(offer.slices)?offer.slices:[]).slice(0,6).map(raw=>{
  const segments=record(raw).segments;if(!Array.isArray(segments)||!segments.length||segments.length>6)throw new FlightError('Flight itinerary is incomplete.',502);
  return segments.map(raw=>{const s=record(raw),airline=record(s.marketing_carrier);const leg={origin:text(record(s.origin).iata_code),destination:text(record(s.destination).iata_code),departure:text(s.departing_at),arrival:text(s.arriving_at),airline:text(airline.name),flightNumber:`${text(airline.iata_code)} ${text(s.marketing_carrier_flight_number)}`.trim(),duration:text(s.duration),originCity:text(record(s.origin).city_name),originName:text(record(s.origin).name),destinationCity:text(record(s.destination).city_name),destinationName:text(record(s.destination).name),cabin:text(record(Array.isArray(s.passengers)?s.passengers[0]:null).cabin_class),operatingAirline:text(record(s.operating_carrier).name),originTimeZone:text(record(s.origin).time_zone),destinationTimeZone:text(record(s.destination).time_zone),stops:(Array.isArray(s.stops)?s.stops:[]).map(raw=>{const stop=record(raw),airport=record(stop.airport);return {airport:text(airport.iata_code),city:text(airport.city_name),name:text(airport.name),arrival:text(stop.arriving_at),departure:text(stop.departing_at),duration:text(stop.duration)}})};
   if(!/^[A-Z]{3}$/.test(leg.origin)||!/^[A-Z]{3}$/.test(leg.destination)||!/^\d{4}-\d{2}-\d{2}T/.test(leg.departure)||!/^\d{4}-\d{2}-\d{2}T/.test(leg.arrival))throw new FlightError('Flight itinerary is incomplete.',502);return leg;});
 });
 if(!slices.length)throw new FlightError('Flight itinerary is incomplete.',502);
 const totalAmount=text(offer.total_amount),totalCurrency=text(offer.total_currency);
 const fare=/^\d+(?:\.\d+)?$/.test(totalAmount)&&Number(totalAmount)>0&&/^[A-Z]{3}$/.test(totalCurrency)?{totalAmount,totalCurrency}:{};
 return {source:'duffel-test',offerId:text(offer.id),retrievedAt:new Date().toISOString(),slices,...fare};
}
export function sampleFlight():FlightItinerary{return {source:'sample',offerId:'sample',retrievedAt:new Date().toISOString(),slices:[[{origin:'CPH',destination:'BKK',departure:'2027-02-10T14:00:00',arrival:'2027-02-11T06:00:00',airline:'Sample airline',flightNumber:'DEMO 101',duration:'PT10H',cabin:'economy'}],[{origin:'BKK',destination:'CPH',departure:'2027-02-24T12:00:00',arrival:'2027-02-24T18:00:00',airline:'Sample airline',flightNumber:'DEMO 102',duration:'PT12H',cabin:'economy'}]]};}
const labels:Record<string,[string,string,string]>={en:['Flight itinerary','Test itinerary — sample schedules, not confirmed flights. Arrange flights separately.','Times are local to each airport.'],da:['Flyrejseplan','Testrejseplan — eksempeltider, ikke bekræftede fly. Fly bestilles separat.','Tiderne er lokale for hver lufthavn.'],sv:['Flygresplan','Testresplan — exempeltider, inga bekräftade flyg. Flyg bokas separat.','Tiderna är lokala för varje flygplats.'],no:['Flyreiseplan','Testreiseplan — eksempeltider, ikke bekreftede fly. Fly bestilles separat.','Tidene er lokale for hver flyplass.'],fr:['Itinéraire aérien','Itinéraire de test — horaires fictifs, vols non confirmés. Réservez les vols séparément.','Les heures sont locales pour chaque aéroport.'],es:['Itinerario de vuelos','Itinerario de prueba — horarios de ejemplo, vuelos sin confirmar. Reserve los vuelos por separado.','Las horas son locales para cada aeropuerto.'],it:['Itinerario dei voli','Itinerario di prova — orari di esempio, voli non confermati. Prenotate i voli separatamente.','Gli orari sono locali per ogni aeroporto.'],nl:['Vluchtschema','Testschema — voorbeeldtijden, geen bevestigde vluchten. Boek vluchten afzonderlijk.','De tijden zijn lokaal voor elke luchthaven.'],hu:['Repülési útiterv','Tesztútiterv — példa menetrend, nem megerősített járatok. A repülőjegyek külön foglalhatók.','Az időpontok az adott repülőtér helyi idejét mutatják.']};
export function renderFlights(value:unknown,locale='en'):string{
 const f=record(value);if(!['sample','duffel-test','serpapi-google-flights'].includes(String(f.source))||!Array.isArray(f.slices))return '';
 const c=labels[locale.split('-')[0]]||labels.en;
 return `<section id="flights" class="stays-section"><div class="brochure-heading"><h2>${c[0]}</h2><p>${f.source==='serpapi-google-flights'?liveFlightNote(locale):c[1]}</p><small>${c[2]}</small></div>${flightTable(f as unknown as FlightItinerary,locale)}</section>`;
}
