import type {FlightItinerary} from './duffel';
const escape=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const headings:Record<string,string[]>={en:['Airline','Date','Departure','Time','Arrival','Time','Flight','Class','Duration'],da:['Flyselskab','Dato','Afgang','Tid','Ankomst','Tid','Fly','Klasse','Rejsetid'],sv:['Flygbolag','Datum','Avgång','Tid','Ankomst','Tid','Flyg','Klass','Restid'],no:['Flyselskap','Dato','Avgang','Tid','Ankomst','Tid','Fly','Klasse','Reisetid'],nl:['Airline','Datum','Vertrek','Tijd','Aankomst','Tijd','Vlucht','Klasse','Reistijd'],fr:['Compagnie','Date','Départ','Heure','Arrivée','Heure','Vol','Classe','Durée'],es:['Aerolínea','Fecha','Salida','Hora','Llegada','Hora','Vuelo','Clase','Duración'],it:['Compagnia','Data','Partenza','Ora','Arrivo','Ora','Volo','Classe','Durata'],hu:['Légitársaság','Dátum','Indulás','Idő','Érkezés','Idő','Járat','Osztály','Időtartam']};
const airports:Record<string,string>={CPH:'Copenhagen',BKK:'Bangkok, Suvarnabhumi',CNX:'Chiang Mai',AMS:'Amsterdam, Schiphol',NRT:'Tokyo, Narita',LHR:'London, Heathrow',HAN:'Hanoi',SGN:'Ho Chi Minh City',DAD:'Da Nang'};
function date(value:string,locale:string){const d=new Date(value.slice(0,10)+'T12:00:00Z');return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat(locale==='en'?'en-GB':locale,{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).format(d)}
function duration(value:string){const m=/^P(?:(\d+)D)?T(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?$/.exec(value);return m?`${Number(m[1]||0)*24+Number(m[2]||0)}h ${Number(m[3]||0)}m`:'—'}
function instant(value:string,zone?:string){
 if(/[Z]|[+-]\d{2}:\d{2}$/.test(value))return Date.parse(value);
 if(!zone)return NaN;
 const target=Date.parse(value+'Z');let guess=target;
 try{for(let i=0;i<3;i++){const parts=new Intl.DateTimeFormat('en-GB',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date(guess));const get=(name:string)=>Number(parts.find(p=>p.type===name)?.value);const local=Date.UTC(get('year'),get('month')-1,get('day'),get('hour'),get('minute'),get('second'));guess+=target-local;}return guess;}catch{return NaN}
}
const stopLabels:Record<string,string[]>={en:['Connection','Stop during this flight','Airport change','Sandbox routing may differ from real flights. Only connections supplied by the test API are shown.'],da:['Flyskifte','Stop under denne flyvning','Lufthavnsskifte','Testruter kan afvige fra virkelige fly. Kun forbindelser fra test-API vises.'],sv:['Anslutning','Stopp under flygningen','Flygplatsbyte','Testrutter kan avvika från verkliga flyg. Endast anslutningar från test-API visas.'],no:['Forbindelse','Stopp under flyvningen','Flyplassbytte','Testruter kan avvike fra virkelige fly. Kun forbindelser fra test-API vises.'],fr:['Correspondance','Escale pendant ce vol','Changement d’aéroport','Les itinéraires de test peuvent différer des vols réels. Seules les correspondances fournies par l’API de test sont affichées.'],es:['Conexión','Escala durante este vuelo','Cambio de aeropuerto','Las rutas de prueba pueden diferir de los vuelos reales. Solo se muestran conexiones de la API de prueba.'],it:['Coincidenza','Scalo durante questo volo','Cambio di aeroporto','Gli itinerari di prova possono differire dai voli reali. Si mostrano solo le coincidenze fornite dall’API di prova.'],nl:['Overstap','Stop tijdens deze vlucht','Luchthavenwissel','Testroutes kunnen afwijken van echte vluchten. Alleen verbindingen uit de test-API worden getoond.'],hu:['Átszállás','Megálló a járat közben','Repülőtérváltás','A tesztútvonalak eltérhetnek a valódi járatoktól. Csak a teszt-API által megadott csatlakozások láthatók.']};
const liveNotes:Record<string,string>={
 en:'Google Flights via SerpApi. Outbound and homebound flights were searched separately as one-way journeys. This is a schedule suggestion, not a combined fare or confirmed booking. Times are local to each airport.',
 da:'Google Flights via SerpApi. Udrejse og hjemrejse er søgt separat som enkeltrejser. Dette er et forslag til flytider, ikke en samlet pris eller bekræftet booking. Tiderne er lokale for hver lufthavn.',
 sv:'Google Flights via SerpApi. Utresa och hemresa har sökts separat som enkelresor. Detta är ett tidtabellsförslag, inte ett totalpris eller en bekräftad bokning. Tiderna är lokala.',
 no:'Google Flights via SerpApi. Utreise og hjemreise er søkt separat som enkeltreiser. Dette er et ruteforslag, ikke en samlet pris eller bekreftet bestilling. Tidene er lokale.',
 fr:'Google Flights via SerpApi. Aller et retour recherchés séparément comme trajets simples. Proposition d’horaires, sans tarif combiné ni réservation confirmée. Heures locales.',
 es:'Google Flights vía SerpApi. Ida y vuelta buscadas por separado como trayectos de solo ida. Propuesta de horarios, sin tarifa conjunta ni reserva confirmada. Horas locales.',
 it:'Google Flights tramite SerpApi. Andata e ritorno cercati separatamente come voli di sola andata. Proposta di orari, senza tariffa combinata né prenotazione confermata. Orari locali.',
 nl:'Google Flights via SerpApi. Heen- en terugvluchten zijn afzonderlijk gezocht als enkele reizen. Een voorstel voor vluchttijden, geen gecombineerd tarief of bevestigde boeking. Lokale tijden.',
 hu:'Google Flights a SerpApi szolgáltatáson keresztül. Az oda- és visszaút külön egyirányú keresés. Menetrendi javaslat, nem kombinált viteldíj vagy megerősített foglalás. Helyi időpontok.'};
export const liveFlightNote=(locale:string)=>liveNotes[locale.split('-')[0]]||liveNotes.en;
export function flightTable(f:FlightItinerary,locale='en'){
 const h=headings[locale.split('-')[0]]||headings.en,c=stopLabels[locale.split('-')[0]]||stopLabels.en;
 const timing=(value:string)=>`${escape(date(value,locale))} · ${escape(value.slice(11,16)||'—')}`;
 const transferLabels:Record<string,string>={en:'Ground transfer needed',da:'Landtransport nødvendig',sv:'Marktransport behövs',no:'Bakketransport trengs',fr:'Transfert terrestre nécessaire',es:'Traslado terrestre necesario',it:'Trasferimento terrestre necessario',nl:'Vervoer over land nodig',hu:'Szárazföldi transzfer szükséges'};
 return `<p class="flight-source-note">${escape(f.source==='serpapi-google-flights'?liveFlightNote(locale):c[3])}</p>${f.transfers?.map(t=>`<p>${escape(transferLabels[locale]||transferLabels.en)}: ${escape(t.place)} ↔ ${escape(t.airportName||airports[t.airport]||t.airport)} (${escape(t.airport)}).</p>`).join('')||''}<div class="flight-table-wrap"><table class="flight-table"><thead><tr>${h.map(x=>`<th scope="col">${x}</th>`).join('')}</tr></thead><tbody>${f.slices.flatMap(slice=>slice.map((s,index)=>{
 const airport=(code:string,city?:string,name?:string)=>`<strong>${escape(city||airports[code]||code)}</strong><small>${escape(name&&name!==city?name+' ': '')}(${escape(code)})</small>`;
 const cabins:Record<string,string>={economy:'Economy',premium_economy:'Premium economy',business:'Business',first:'First'};
 const values=[`${escape(s.airline)}${s.operatingAirline&&s.operatingAirline!==s.airline?`<small>${escape(s.operatingAirline)}</small>`:''}`,date(s.departure,locale),airport(s.origin,s.originCity,s.originName),`<strong>${escape(s.departure.slice(11,16))}</strong>`,airport(s.destination,s.destinationCity,s.destinationName),`<strong>${escape(s.arrival.slice(11,16))}</strong><small>${escape(date(s.arrival,locale))}</small>`,escape(s.flightNumber),escape(cabins[s.cabin||'']||s.cabin||'—'),duration(s.duration)];
 const row=`<tr>${values.map((x,i)=>`<td data-label="${escape(i===3?h[2]+' · '+h[3]:i===5?h[4]+' · '+h[5]:h[i])}">${x}</td>`).join('')}</tr>`;
 const stops=(s.stops||[]).map(stop=>`<tr class="flight-connection"><td colspan="9"><strong>${escape(c[1])}: ${escape(stop.city||airports[stop.airport]||stop.airport)} (${escape(stop.airport)})</strong>${escape(h[4])}: ${timing(stop.arrival)} · ${escape(h[2])}: ${timing(stop.departure)} · ${escape(h[8])}: ${duration(stop.duration)}</td></tr>`).join('');
 const next=slice[index+1];if(!next)return row+stops;
 const minutes=Math.round((instant(next.departure,next.originTimeZone)-instant(s.arrival,s.destinationTimeZone))/60000);
 const same=s.destination===next.origin;
 const wait=same&&s.connectionDuration?duration(s.connectionDuration):same&&Number.isFinite(minutes)&&minutes>=0?`${Math.floor(minutes/60)}h ${minutes%60}m`:'—';
 return row+stops+`<tr class="flight-connection"><td colspan="9"><strong>${escape(same?c[0]:c[2])}: ${escape(s.destinationCity||airports[s.destination]||s.destination)} (${escape(s.destination)})${same?'':` → ${escape(next.originCity||airports[next.origin]||next.origin)} (${escape(next.origin)})`}</strong>${escape(h[4])}: ${timing(s.arrival)} · ${escape(h[2])}: ${timing(next.departure)} · ${escape(h[8])}: ${wait}</td></tr>`;
 })).join('')}</tbody></table></div>`;
}
