import type {FlightItinerary} from './duffel';
const escape=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const headings:Record<string,string[]>={en:['Airline','Date','Departure','Time','Arrival','Time','Flight','Class','Duration'],da:['Flyselskab','Dato','Afgang','Tid','Ankomst','Tid','Fly','Klasse','Rejsetid'],sv:['Flygbolag','Datum','Avgång','Tid','Ankomst','Tid','Flyg','Klass','Restid'],no:['Flyselskap','Dato','Avgang','Tid','Ankomst','Tid','Fly','Klasse','Reisetid'],nl:['Airline','Datum','Vertrek','Tijd','Aankomst','Tijd','Vlucht','Klasse','Reistijd'],fr:['Compagnie','Date','Départ','Heure','Arrivée','Heure','Vol','Classe','Durée'],es:['Aerolínea','Fecha','Salida','Hora','Llegada','Hora','Vuelo','Clase','Duración'],it:['Compagnia','Data','Partenza','Ora','Arrivo','Ora','Volo','Classe','Durata'],hu:['Légitársaság','Dátum','Indulás','Idő','Érkezés','Idő','Járat','Osztály','Időtartam']};
const airports:Record<string,string>={CPH:'Copenhagen',BKK:'Bangkok, Suvarnabhumi',CNX:'Chiang Mai',AMS:'Amsterdam, Schiphol',NRT:'Tokyo, Narita',LHR:'London, Heathrow'};
function date(value:string,locale:string){const d=new Date(value.slice(0,10)+'T12:00:00Z');return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat(locale==='en'?'en-GB':locale,{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).format(d)}
function duration(value:string){const m=/^P(?:(\d+)D)?T(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?$/.exec(value);return m?`${Number(m[1]||0)*24+Number(m[2]||0)}h ${Number(m[3]||0)}m`:'—'}
export const flightTableStyles=`.flight-table-wrap{width:100%;margin:16px 0;overflow:auto}.flight-table{width:100%;border-collapse:collapse;font-size:14px;text-align:left;background:#fffdf8}.flight-table th{background:#eeeae2;color:#45534b;font-size:11px;text-transform:uppercase;letter-spacing:.04em}.flight-table th,.flight-table td{padding:12px 10px;border-bottom:1px solid #dcd8ce;vertical-align:top}.flight-table td strong{display:block;font-size:16px;color:#17382e}.flight-table td small{display:block;color:#5c6961;margin-top:4px}.planner-flights .hotel-options{display:block}.planner-flights .hotel-option{display:flex;margin:14px 0;padding:16px;border:1px solid #dcd8ce;border-radius:8px}.planner-flights .hotel-option>div{min-width:0;width:100%}@media(max-width:700px){.flight-table thead{display:none}.flight-table,.flight-table tbody{display:block}.flight-table tr{display:grid;grid-template-columns:1fr 1fr;border-bottom:2px solid #dcd8ce;padding:8px}.flight-table td{display:block;border:0;padding:8px;font-size:13px}.flight-table td:before{content:attr(data-label);display:block;font-size:10px;text-transform:uppercase;color:#5c6961;margin-bottom:5px}.flight-table td:nth-child(1){grid-column:1/-1;order:1}.flight-table td:nth-child(2){grid-column:1/-1;order:2}.flight-table td:nth-child(3){order:3}.flight-table td:nth-child(5){order:4}.flight-table td:nth-child(4){order:5}.flight-table td:nth-child(6){order:6}.flight-table td:nth-child(7){order:7}.flight-table td:nth-child(8){order:8}.flight-table td:nth-child(9){order:9}.flight-table td strong{font-size:15px}.planner-flights .hotel-option{padding:10px}}`;
export function flightTable(f:FlightItinerary,locale='en'){
 const h=headings[locale.split('-')[0]]||headings.en;
 return `<div class="flight-table-wrap"><table class="flight-table"><thead><tr>${h.map(x=>`<th scope="col">${x}</th>`).join('')}</tr></thead><tbody>${f.slices.flatMap(slice=>slice.map(s=>{
 const airport=(code:string,city?:string,name?:string)=>`<strong>${escape(city||airports[code]||code)}</strong><small>${escape(name&&name!==city?name+' ': '')}(${escape(code)})</small>`;
 const cabins:Record<string,string>={economy:'Economy',premium_economy:'Premium economy',business:'Business',first:'First'};
 const values=[`${escape(s.airline)}${s.operatingAirline&&s.operatingAirline!==s.airline?`<small>${escape(s.operatingAirline)}</small>`:''}`,date(s.departure,locale),airport(s.origin,s.originCity,s.originName),`<strong>${escape(s.departure.slice(11,16))}</strong>`,airport(s.destination,s.destinationCity,s.destinationName),`<strong>${escape(s.arrival.slice(11,16))}</strong><small>${escape(date(s.arrival,locale))}</small>`,escape(s.flightNumber),escape(cabins[s.cabin||'']||s.cabin||'—'),duration(s.duration)];
 return `<tr>${values.map((x,i)=>`<td data-label="${escape(i===3?h[2]+' · '+h[3]:i===5?h[4]+' · '+h[5]:h[i])}">${x}</td>`).join('')}</tr>`;
 })).join('')}</tbody></table></div>`;
}
