// Customer copy for confirmed scope; never infer contractual inclusions from itinerary mentions.
const copy:Record<string,string[]>={
 en:['What your proposal covers','Included','Not included','To be confirmed','No services have yet been confirmed as included in the price.','No exclusions have yet been confirmed.','Selected accommodation, room categories and availability','Meals and breakfast','Transfers, domestic transport, domestic and international flights','Guides, activities and entrance fees','Insurance, visas, tips, personal expenses and optional activities','This is a planning estimate. Your consultant will confirm the service breakdown and final price before booking.','Planned nights','Property source awaiting verification'],
 da:['Hvad dit forslag omfatter','Inkluderet','Ikke inkluderet','Skal bekræftes','Ingen ydelser er endnu bekræftet som inkluderet i prisen.','Det er endnu ikke bekræftet, hvilke ydelser der ikke er inkluderet.','Valgte hoteller, værelsestyper og tilgængelighed','Måltider og morgenmad','Transfers, indenrigstransport samt indenrigs- og internationale fly','Guider, aktiviteter og entré','Forsikring, visa, drikkepenge, personlige udgifter og valgfrie aktiviteter','Dette er et prisoverslag. Din konsulent bekræfter ydelser og endelig pris før booking.','Planlagte nætter','Hotelkilde afventer kontrol'],
 sv:['Vad ditt förslag omfattar','Ingår','Ingår inte','Ska bekräftas','Inga tjänster har ännu bekräftats som inkluderade i priset.','Det är ännu inte bekräftat vilka tjänster som inte ingår.','Valda boenden, rumstyper och tillgänglighet','Måltider och frukost','Transfer, inrikestransporter samt inrikes- och internationella flyg','Guider, aktiviteter och inträden','Försäkring, visum, dricks, personliga utgifter och valfria aktiviteter','Detta är en prisuppskattning. Din konsult bekräftar tjänster och slutpris före bokning.','Planerade nätter','Hotellkälla väntar på kontroll'],
 no:['Hva forslaget omfatter','Inkludert','Ikke inkludert','Må bekreftes','Ingen tjenester er ennå bekreftet som inkludert i prisen.','Det er ennå ikke bekreftet hvilke tjenester som ikke er inkludert.','Valgte overnattingssteder, romtyper og tilgjengelighet','Måltider og frokost','Transfer, innenrikstransport samt innenriks- og internasjonale fly','Guider, aktiviteter og inngangsbilletter','Forsikring, visum, tips, personlige utgifter og valgfrie aktiviteter','Dette er et prisoverslag. Konsulenten bekrefter tjenester og endelig pris før bestilling.','Planlagte netter','Hotellkilde venter på kontroll'],
 es:['Qué cubre tu propuesta','Incluido','No incluido','Por confirmar','Aún no se ha confirmado ningún servicio como incluido en el precio.','Aún no se han confirmado exclusiones.','Alojamientos elegidos, tipos de habitación y disponibilidad','Comidas y desayuno','Traslados, transporte y vuelos nacionales e internacionales','Guías, actividades y entradas','Seguro, visados, propinas, gastos personales y actividades opcionales','Esta es una estimación. Tu asesor confirmará los servicios y el precio final antes de reservar.','Noches previstas','Fuente del hotel pendiente de verificación'],
 fr:['Ce que couvre votre proposition','Inclus','Non inclus','À confirmer','Aucun service n’a encore été confirmé comme inclus dans le prix.','Aucune exclusion n’a encore été confirmée.','Hébergements choisis, catégories de chambre et disponibilité','Repas et petit-déjeuner','Transferts, transports et vols intérieurs et internationaux','Guides, activités et entrées','Assurance, visas, pourboires, dépenses personnelles et activités facultatives','Ceci est une estimation. Votre conseiller confirmera les services et le prix final avant réservation.','Nuits prévues','Source de l’hôtel à vérifier'],
 it:['Cosa comprende la proposta','Incluso','Non incluso','Da confermare','Nessun servizio è ancora confermato come incluso nel prezzo.','Nessuna esclusione è ancora confermata.','Alloggi scelti, categorie di camera e disponibilità','Pasti e colazione','Trasferimenti, trasporti e voli interni e internazionali','Guide, attività e ingressi','Assicurazione, visti, mance, spese personali e attività facoltative','Questa è una stima. Il consulente confermerà servizi e prezzo finale prima della prenotazione.','Notti previste','Fonte dell’hotel da verificare'],
 nl:['Wat je voorstel omvat','Inbegrepen','Niet inbegrepen','Nog te bevestigen','Er zijn nog geen diensten bevestigd als inbegrepen in de prijs.','Er zijn nog geen uitsluitingen bevestigd.','Gekozen accommodaties, kamertypes en beschikbaarheid','Maaltijden en ontbijt','Transfers, binnenlands vervoer en binnenlandse en internationale vluchten','Gidsen, activiteiten en entreegelden','Verzekering, visa, fooien, persoonlijke uitgaven en optionele activiteiten','Dit is een raming. Je adviseur bevestigt de diensten en de definitieve prijs vóór boeking.','Geplande nachten','Hotelbron wacht op verificatie'],
 hu:['Mit tartalmaz az ajánlat','Tartalmazza','Nem tartalmazza','Megerősítendő','Még nincs az árban foglaltként megerősített szolgáltatás.','Még nincsenek megerősített kizárások.','Kiválasztott szállások, szobatípusok és elérhetőség','Étkezések és reggeli','Transzferek, belföldi közlekedés, belföldi és nemzetközi repülőjáratok','Idegenvezetők, programok és belépők','Biztosítás, vízumok, borravaló, személyes kiadások és választható programok','Ez becslés. Tanácsadója foglalás előtt megerősíti a szolgáltatásokat és a végleges árat.','Tervezett éjszakák','A szálloda forrása ellenőrzésre vár'],
};
export function serviceCopy(locale:string){const v=copy[locale.split('-')[0]]||copy.en;return {title:v[0],included:v[1],excluded:v[2],pending:v[3],empty:v[4],flights:v[5],pendingItems:v.slice(6,11),help:v[11],nights:v[12],source:v[13]};}
