import type { Locale } from '../i18n';
export type CountrySlug='china'|'japan'|'thailand'|'vietnam'|'indonesia';
export type PriceMap={USD:number;EUR:number;DKK:number;SEK:number;NOK:number;HUF:number};
export interface Country {slug:CountrySlug; name:string; nativeName:string; code:string; hero:string; tile:string; alt:string; intro:string; regions:{name:string;copy:string}[]; practical:string[]; gallery:string[]}
export interface Tour {slug:string;country:CountrySlug;name:string;duration:number;prices:PriceMap;image:string;teaser:string;groupSize:string;departures:string[];includes:string[];excludes:string[];itinerary:{day:string;title:string;copy:string}[]}
const u=(id:string,w=1800)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=84`;
export const countries:Country[]=[
{slug:'china',name:'China',nativeName:'中国',code:'PEK',hero:u('photo-1508804185872-d7badad00f7d'),tile:u('photo-1508804185872-d7badad00f7d'),alt:'The Great Wall winding through green mountains',intro:'Ancient dynasties and restless megacities share the same horizon. China rewards time: a tea poured slowly, a courtyard at dawn, a mountain path beyond the crowds.',regions:[{name:'Beijing',copy:'Imperial scale, neighbourhood intimacy and the northern table.'},{name:'Yunnan',copy:'Highland cultures, old tea routes and dramatic valleys.'},{name:'Shanghai',copy:'Art deco lanes and contemporary China at full velocity.'}],practical:['Spring and autumn offer the gentlest weather.','High-speed rail makes longer routes remarkably fluid.','Visa requirements vary; we advise for each passport.'],gallery:[u('photo-1537531383496-f4749b8032cf'),u('photo-1523731407965-2430cd12f5e4'),u('photo-1547981609-4b6bfe67ca0b')]},
{slug:'japan',name:'Japan',nativeName:'日本',code:'NRT',hero:u('photo-1528360983277-13d401cdc186'),tile:u('photo-1528360983277-13d401cdc186'),alt:'Traditional Japanese pagoda with Mount Fuji beyond',intro:'Japan balances exacting craft with effortless beauty. We move between Tokyo’s small bars, temple gardens in Kyoto and the quiet edges of the archipelago.',regions:[{name:'Tokyo',copy:'A collection of villages disguised as a metropolis.'},{name:'Kyoto',copy:'Temples, gardens and living traditions of remarkable subtlety.'},{name:'Hokkaido',copy:'Wild landscapes, hot springs and a distinct northern cuisine.'}],practical:['Cherry blossom and autumn colour require early planning.','The rail network is precise, comfortable and extensive.','Etiquette is nuanced; a little context opens many doors.'],gallery:[u('photo-1524413840807-0c3cb6fa808d'),u('photo-1528164344705-47542687000d'),u('photo-1492571350019-22de08371fd3')]},
{slug:'thailand',name:'Thailand',nativeName:'ประเทศไทย',code:'BKK',hero:u('photo-1528181304800-259b08848526'),tile:u('photo-1528181304800-259b08848526'),alt:'Long-tail boats in a limestone bay in Thailand',intro:'Thailand’s warmth is more than climate. Markets, forest temples and island mornings come together through a culture of welcome and an extraordinary food tradition.',regions:[{name:'Bangkok',copy:'River life, gilded temples and some of Asia’s most vivid cooking.'},{name:'Chiang Mai',copy:'Northern craft, mountain landscapes and Lanna heritage.'},{name:'The South',copy:'Limestone bays and quiet islands chosen for season and character.'}],practical:['November to February is dry in much of the country.','Domestic flights pair well with selective road and boat travel.','Shoulders and knees should be covered at temples.'],gallery:[u('photo-1552465011-b4e21bf6e79a'),u('photo-1537996194471-e657df975ab4'),u('photo-1552550018-5253c1b171e1')]},
{slug:'vietnam',name:'Vietnam',nativeName:'Việt Nam',code:'SGN',hero:u('photo-1528127269322-539801943592'),tile:u('photo-1528127269322-539801943592'),alt:'Green limestone landscape and river in Vietnam',intro:'A long, generous country of layered history, vivid street food and landscapes that change with every latitude. Vietnam is best experienced as a rhythm, not a checklist.',regions:[{name:'Hanoi & North',copy:'Lake mornings, old quarters and mountains shaped by rice terraces.'},{name:'Central Coast',copy:'Imperial Hue, lantern-lit Hoi An and long beaches.'},{name:'Saigon & Delta',copy:'Energy, architecture and the waterways of the Mekong.'}],practical:['Weather differs sharply between north, centre and south.','Short flights connect regions; trains reveal the landscape.','E-visas are available to many nationalities.'],gallery:[u('photo-1521993117367-b7f70ccd029d'),u('photo-1509030450996-dd1a26dda07a'),u('photo-1540611025311-01df3cef54b5')]},
{slug:'indonesia',name:'Indonesia',nativeName:'Indonesia',code:'DPS',hero:u('photo-1533669955142-6a73332af4db'),tile:u('photo-1537996194471-e657df975ab4'),alt:'Rice terraces glowing in morning light in Indonesia',intro:'Across thousands of islands, Indonesia offers volcanic landscapes, layered spiritual traditions and coastlines that invite a slower sense of time.',regions:[{name:'Bali',copy:'Ritual, craft and landscapes beyond the familiar shoreline.'},{name:'Java',copy:'Volcano dawns, royal cities and monumental Borobudur.'},{name:'Komodo & Flores',copy:'Elemental islands, exceptional reefs and small-ship exploration.'}],practical:['Dry season generally runs from April to October.','Island routes combine flights, boats and private road transfers.','Temple and village visits call for respectful dress.'],gallery:[u('photo-1518548419970-58e3b4079ab2'),u('photo-1539367628448-4bc5c9d171c8'),u('photo-1577717903315-1691ae25ab3f')]}
];
const prices=(USD:number,EUR:number,DKK:number,SEK:number,NOK:number,HUF:number):PriceMap=>({USD,EUR,DKK,SEK,NOK,HUF});
export const tours:Tour[]=[
{slug:'silk-and-courtyards',country:'china',name:'Silk & Courtyards',duration:12,prices:prices(7200,6600,49200,73800,76800,2590000),image:u('photo-1508804185872-d7badad00f7d',1200),teaser:'Beijing’s hidden lanes, the Great Wall at first light and Yunnan’s old tea road.',groupSize:'Private · 2–8 guests',departures:['Mar–May','Sep–Nov'],includes:['Private guides','Boutique accommodation','Internal transport','Daily breakfast'],excludes:['International flights','Travel insurance'],itinerary:[{day:'01–03',title:'Beijing, behind the walls',copy:'Settle into a courtyard hotel and explore imperial Beijing through its quieter thresholds.'},{day:'04–05',title:'The Great Wall',copy:'Walk an unrestored section at an unhurried pace and stay in a mountain village.'},{day:'06–12',title:'The Yunnan tea road',copy:'Fly south for Dali, Shaxi and village stays beneath the Himalaya.'}]},
{slug:'japan-in-stillness',country:'japan',name:'Japan in Stillness',duration:14,prices:prices(8900,8200,61200,91600,95400,3220000),image:u('photo-1528360983277-13d401cdc186',1200),teaser:'Tokyo detail, Kyoto gardens and the contemplative shores of Naoshima.',groupSize:'Private · 2–6 guests',departures:['Mar–May','Oct–Nov'],includes:['Expert guides','Design hotels & ryokan','Rail passes','Selected dinners'],excludes:['International flights','Travel insurance'],itinerary:[{day:'01–04',title:'Tokyo in detail',copy:'Architecture, neighbourhood kitchens and an after-hours studio visit.'},{day:'05–09',title:'Kyoto, slowly',copy:'Garden walks before opening, craft ateliers and a temple lodging.'},{day:'10–14',title:'Art islands',copy:'Travel west to Naoshima and Teshima for art, sea and silence.'}]},
{slug:'northern-table-southern-sea',country:'thailand',name:'Northern Table, Southern Sea',duration:11,prices:prices(5400,4950,36900,55300,57600,1940000),image:u('photo-1528181304800-259b08848526',1200),teaser:'Bangkok kitchens, Lanna craft and an island chosen for the season.',groupSize:'Private · 2–10 guests',departures:['Nov–Mar'],includes:['Private guides','Boutique hotels','Domestic flights','Food experiences'],excludes:['International flights','Travel insurance'],itinerary:[{day:'01–03',title:'Bangkok by river',copy:'Begin on the Chao Phraya, then taste the city with a chef.'},{day:'04–07',title:'The northern table',copy:'Meet growers and makers outside Chiang Mai.'},{day:'08–11',title:'A quieter island',copy:'Fly south for a low-key beach hideaway matched to the season.'}]},
{slug:'vietnam-long-table',country:'vietnam',name:'Vietnam, Long Table',duration:13,prices:prices(6100,5600,41800,62500,65100,2200000),image:u('photo-1528127269322-539801943592',1200),teaser:'A culinary thread from Hanoi’s alleys to the gardens of the Mekong.',groupSize:'Small group · 6–12 guests',departures:['Feb','Mar','Nov'],includes:['Tour leader','Character hotels','Domestic transport','Most meals'],excludes:['International flights','Travel insurance'],itinerary:[{day:'01–04',title:'Hanoi appetites',copy:'Markets, family kitchens and a private table with a young chef.'},{day:'05–08',title:'The central coast',copy:'Hue gardens and Hoi An’s fishing villages.'},{day:'09–13',title:'Saigon & Mekong',copy:'Contemporary Saigon followed by two nights on the delta.'}]},
{slug:'islands-of-fire-and-water',country:'indonesia',name:'Islands of Fire & Water',duration:15,prices:prices(7900,7250,54100,80900,84400,2850000),image:u('photo-1533669955142-6a73332af4db',1200),teaser:'Temple dawns in Java, ritual Bali and a private boat through Komodo.',groupSize:'Private · 2–8 guests',departures:['Apr–Oct'],includes:['Private guides','Boutique stays','Private Komodo boat','Domestic transport'],excludes:['International flights','Travel insurance'],itinerary:[{day:'01–05',title:'Java, monumental',copy:'Yogyakarta’s arts and sunrise at Borobudur.'},{day:'06–10',title:'Bali beyond the coast',copy:'Walk water temples, valleys and artist villages.'},{day:'11–15',title:'Komodo by sea',copy:'Three nights aboard a private phinisi among wild islands.'}]}
];
export function getCountry(slug:string){return countries.find(c=>c.slug===slug)}
export function getTour(country:string,slug:string){return tours.find(t=>t.country===country&&t.slug===slug)}
export const currencyForLocale:Record<Locale,keyof PriceMap>={en:'USD',es:'EUR',it:'EUR',fr:'EUR',nl:'EUR',hu:'HUF',sv:'SEK',da:'DKK',no:'NOK'};
