import {useMemo,useState,type SyntheticEvent} from 'react';
import {hbxGateways,type HbxAvailabilityResponse} from '../lib/suppliers/availability';

type Locale='en'|'es'|'it'|'fr'|'nl'|'hu'|'sv'|'da'|'no';
type Copy={title:string;intro:string;gateway:string;arrival:string;nights:string;adults:string;children:string;ages:string;agesHelp:string;check:string;checking:string;notice:string;empty:string;error:string;headings:Record<string,string>;status:Record<string,string>};
const copy:Record<Locale,Copy>={
  en:{title:'Check the HBX sandbox',intro:'Run a read-only evaluation search for hotel, activity and airport-transfer availability. Nothing can be booked.',gateway:'Gateway',arrival:'Arrival date',nights:'Nights',adults:'Adults',children:'Children',ages:'Child ages',agesHelp:'Comma-separated, for example 4, 9',check:'Check sandbox availability',checking:'Checking HBX…',notice:'Evaluation data only · Prices require recheck · No booking or payment',empty:'No sandbox offers returned.',error:'Check the date and traveller details.',headings:{accommodation:'Hotels',activity:'Activities',transfer:'Airport transfers'},status:{none:'No results',unavailable:'Temporarily unavailable',skipped:'Not checked'}},
  da:{title:'Tjek HBX-sandkassen',intro:'Kør en skrivebeskyttet testsøgning efter hoteller, aktiviteter og lufthavnstransfer. Intet kan bookes.',gateway:'Ankomstby',arrival:'Ankomstdato',nights:'Nætter',adults:'Voksne',children:'Børn',ages:'Børnenes alder',agesHelp:'Adskilt med komma, fx 4, 9',check:'Tjek tilgængelighed i sandkassen',checking:'Tjekker HBX…',notice:'Kun testdata · Priser skal kontrolleres igen · Ingen booking eller betaling',empty:'Ingen testtilbud fundet.',error:'Kontrollér dato og oplysninger om de rejsende.',headings:{accommodation:'Hoteller',activity:'Aktiviteter',transfer:'Lufthavnstransfer'},status:{none:'Ingen resultater',unavailable:'Midlertidigt utilgængelig',skipped:'Ikke kontrolleret'}},
  es:{title:'Consultar el entorno de pruebas HBX',intro:'Realiza una búsqueda de evaluación de solo lectura para hoteles, actividades y traslados. No se puede reservar.',gateway:'Ciudad de llegada',arrival:'Fecha de llegada',nights:'Noches',adults:'Adultos',children:'Niños',ages:'Edades de los niños',agesHelp:'Separadas por comas, por ejemplo 4, 9',check:'Consultar disponibilidad de prueba',checking:'Consultando HBX…',notice:'Solo datos de evaluación · Precios sujetos a revisión · Sin reservas ni pagos',empty:'No se encontraron ofertas de prueba.',error:'Revisa la fecha y los viajeros.',headings:{accommodation:'Hoteles',activity:'Actividades',transfer:'Traslados al aeropuerto'},status:{none:'Sin resultados',unavailable:'No disponible temporalmente',skipped:'No consultado'}},
  it:{title:'Verifica la sandbox HBX',intro:'Esegui una ricerca di valutazione in sola lettura per hotel, attività e trasferimenti. Non è possibile prenotare.',gateway:'Città di arrivo',arrival:'Data di arrivo',nights:'Notti',adults:'Adulti',children:'Bambini',ages:'Età dei bambini',agesHelp:'Separate da virgole, ad esempio 4, 9',check:'Verifica disponibilità sandbox',checking:'Verifica HBX…',notice:'Solo dati di valutazione · Prezzi da ricontrollare · Nessuna prenotazione o pagamento',empty:'Nessuna offerta sandbox trovata.',error:'Controlla data e viaggiatori.',headings:{accommodation:'Hotel',activity:'Attività',transfer:'Trasferimenti aeroportuali'},status:{none:'Nessun risultato',unavailable:'Temporaneamente non disponibile',skipped:'Non verificato'}},
  fr:{title:'Consulter le bac à sable HBX',intro:'Lancez une recherche d’évaluation en lecture seule pour hôtels, activités et transferts. Aucune réservation possible.',gateway:'Ville d’arrivée',arrival:'Date d’arrivée',nights:'Nuits',adults:'Adultes',children:'Enfants',ages:'Âge des enfants',agesHelp:'Séparés par des virgules, par exemple 4, 9',check:'Consulter les disponibilités test',checking:'Interrogation de HBX…',notice:'Données d’évaluation uniquement · Prix à revérifier · Aucune réservation ni paiement',empty:'Aucune offre test trouvée.',error:'Vérifiez la date et les voyageurs.',headings:{accommodation:'Hôtels',activity:'Activités',transfer:'Transferts aéroport'},status:{none:'Aucun résultat',unavailable:'Temporairement indisponible',skipped:'Non vérifié'}},
  nl:{title:'Controleer de HBX-sandbox',intro:'Voer een alleen-lezen evaluatiezoekopdracht uit voor hotels, activiteiten en transfers. Boeken is niet mogelijk.',gateway:'Aankomststad',arrival:'Aankomstdatum',nights:'Nachten',adults:'Volwassenen',children:'Kinderen',ages:'Leeftijden kinderen',agesHelp:'Met komma’s, bijvoorbeeld 4, 9',check:'Controleer sandbox-beschikbaarheid',checking:'HBX wordt gecontroleerd…',notice:'Alleen evaluatiegegevens · Prijzen opnieuw controleren · Geen boeking of betaling',empty:'Geen sandbox-aanbod gevonden.',error:'Controleer datum en reizigers.',headings:{accommodation:'Hotels',activity:'Activiteiten',transfer:'Luchthaventransfers'},status:{none:'Geen resultaten',unavailable:'Tijdelijk niet beschikbaar',skipped:'Niet gecontroleerd'}},
  hu:{title:'HBX tesztkörnyezet ellenőrzése',intro:'Csak olvasható tesztkeresés szállodákra, programokra és transzferekre. Foglalás nem lehetséges.',gateway:'Érkezési város',arrival:'Érkezés dátuma',nights:'Éjszakák',adults:'Felnőttek',children:'Gyerekek',ages:'Gyerekek életkora',agesHelp:'Vesszővel elválasztva, például 4, 9',check:'Tesztelérhetőség ellenőrzése',checking:'HBX ellenőrzése…',notice:'Csak tesztadat · Az árakat újra kell ellenőrizni · Nincs foglalás vagy fizetés',empty:'Nincs tesztajánlat.',error:'Ellenőrizze a dátumot és az utasokat.',headings:{accommodation:'Szállodák',activity:'Programok',transfer:'Repülőtéri transzferek'},status:{none:'Nincs eredmény',unavailable:'Átmenetileg nem elérhető',skipped:'Nincs ellenőrizve'}},
  sv:{title:'Kontrollera HBX-sandlådan',intro:'Gör en skrivskyddad testsökning efter hotell, aktiviteter och flygplatstransfer. Inget kan bokas.',gateway:'Ankomststad',arrival:'Ankomstdatum',nights:'Nätter',adults:'Vuxna',children:'Barn',ages:'Barnens ålder',agesHelp:'Kommaseparerat, till exempel 4, 9',check:'Kontrollera testtillgänglighet',checking:'Kontrollerar HBX…',notice:'Endast testdata · Priser måste kontrolleras igen · Ingen bokning eller betalning',empty:'Inga testerbjudanden hittades.',error:'Kontrollera datum och resenärer.',headings:{accommodation:'Hotell',activity:'Aktiviteter',transfer:'Flygplatstransfer'},status:{none:'Inga resultat',unavailable:'Tillfälligt otillgänglig',skipped:'Inte kontrollerat'}},
  no:{title:'Sjekk HBX-sandkassen',intro:'Kjør et skrivebeskyttet testsøk etter hoteller, aktiviteter og flyplasstransport. Ingenting kan bestilles.',gateway:'Ankomstby',arrival:'Ankomstdato',nights:'Netter',adults:'Voksne',children:'Barn',ages:'Barnas alder',agesHelp:'Kommaseparert, for eksempel 4, 9',check:'Sjekk testtilgjengelighet',checking:'Sjekker HBX…',notice:'Kun testdata · Priser må kontrolleres på nytt · Ingen bestilling eller betaling',empty:'Ingen testtilbud funnet.',error:'Kontroller dato og reisende.',headings:{accommodation:'Hoteller',activity:'Aktiviteter',transfer:'Flyplasstransport'},status:{none:'Ingen resultater',unavailable:'Midlertidig utilgjengelig',skipped:'Ikke kontrollert'}},
};

const currencyFor=(locale:Locale)=>locale==='da'?'DKK':locale==='sv'?'SEK':locale==='no'?'NOK':locale==='hu'?'HUF':'EUR';
const tomorrow=()=>{const date=new Date();date.setDate(date.getDate()+30);return date.toISOString().slice(0,10)};

export default function HbxAvailability({locale='en',preferredCountry}:{locale?:Locale;preferredCountry?:string}){
  const c=copy[locale]??copy.en;
  const initialGateway=useMemo(()=>Object.values(hbxGateways).find(item=>item.country===preferredCountry)?.id??'bangkok',[preferredCountry]);
  const [result,setResult]=useState<HbxAvailabilityResponse|null>(null);
  const [status,setStatus]=useState<'idle'|'loading'|'error'>('idle');
  const [error,setError]=useState('');
  async function submit(event:SyntheticEvent<HTMLFormElement>){
    event.preventDefault();const data=new FormData(event.currentTarget);const childAges=String(data.get('childAges')||'').split(',').map(value=>value.trim()).filter(Boolean).map(Number);const children=Number(data.get('children'));
    if(children!==childAges.length||childAges.some(age=>!Number.isInteger(age)||age<0||age>17)){setError(c.error);setStatus('error');return}
    setStatus('loading');setError('');setResult(null);
    try{const response=await fetch('/api/supplier-availability',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({locale,gateway:data.get('gateway'),checkIn:data.get('checkIn'),nights:Number(data.get('nights')),adults:Number(data.get('adults')),childAges,currency:currencyFor(locale)})});const body=await response.json() as HbxAvailabilityResponse&{error?:string};if(!response.ok)throw new Error(body.error||c.error);setResult(body);setStatus('idle')}catch(reason){setError(reason instanceof Error?reason.message:c.error);setStatus('error')}
  }
  return <section className="hbx-check"><header><span className="agent-mark">HBX · Evaluation</span><h3>{c.title}</h3><p>{c.intro}</p></header><form onSubmit={submit}><label>{c.gateway}<select name="gateway" defaultValue={initialGateway}>{Object.values(hbxGateways).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>{c.arrival}<input type="date" name="checkIn" min={new Date().toISOString().slice(0,10)} defaultValue={tomorrow()} required/></label><label>{c.nights}<input type="number" name="nights" min="1" max="35" defaultValue="7" required/></label><label>{c.adults}<input type="number" name="adults" min="1" max="12" defaultValue="2" required/></label><label>{c.children}<input type="number" name="children" min="0" max="8" defaultValue="0" aria-describedby="child-age-help"/></label><label>{c.ages}<input type="text" name="childAges" inputMode="numeric" placeholder="4, 9"/><small id="child-age-help">{c.agesHelp}</small></label><button className="secondary" type="submit" disabled={status==='loading'}>{status==='loading'?c.checking:c.check}</button></form><p className="hbx-notice">{c.notice}</p>{error&&<p className="form-error" role="alert">{error}</p>}{result&&<div className="availability-results">{result.sections.map(section=><section key={section.vertical}><div><h4>{c.headings[section.vertical]}</h4><span>{section.status==='available'?`${section.offers.length} live test result${section.offers.length===1?'':'s'}`:c.status[section.status]??section.status}</span></div>{section.offers.length?<ul>{section.offers.map((offer,index)=><li key={`${offer.title}-${index}`}><b>{offer.title}</b><p>{offer.summary}</p><strong>{new Intl.NumberFormat(locale,{style:'currency',currency:offer.total.currency}).format(offer.total.amountMinor/100)}</strong></li>)}</ul>:<p>{section.message||c.empty}</p>}</section>)}</div>}</section>;
}
