import type {PlannerFlights as FlightPlan} from '../../functions/_lib/planner-flights';
import type {FlightItinerary} from '../../functions/_lib/duffel';
const copy:Record<string,string[]>={
en:['Flights for your journey','Test schedules only. Flights are not confirmed and must be arranged separately. Times are local to each airport.','Flight search will be available once our test connection is configured.','Flight search needs recognised departure and route airports, dates and an adult-only party of up to nine. A consultant can help clarify the details.','No suitable test flights were returned for the journey dates and airports. Your consultant can review the routing.','Suggested itinerary','No flight itinerary selected'],
da:['Fly til din rejse','Kun testtider. Fly er ikke bekræftet og bestilles separat. Tiderne er lokale for hver lufthavn.','Flysøgning bliver tilgængelig, når vores testforbindelse er konfigureret.','Flysøgning kræver kendte lufthavne, datoer og højst ni voksne uden børn. En konsulent kan hjælpe med detaljerne.','Der blev ikke fundet passende testfly til rejsens datoer og lufthavne. Din konsulent kan gennemgå ruten.','Foreslået flyrejseplan','Ingen flyrejseplan valgt'],
sv:['Flyg för din resa','Endast testtider. Flygen är inte bekräftade och bokas separat. Tiderna är lokala för varje flygplats.','Flygsökning blir tillgänglig när vår testanslutning är konfigurerad.','Flygsökning kräver kända flygplatser, datum och högst nio vuxna utan barn. En konsult kan hjälpa med detaljerna.','Inga lämpliga testflyg hittades för resans datum och flygplatser. Din konsult kan granska rutten.','Föreslagen flygresplan','Ingen flygresplan vald'],
no:['Fly til reisen din','Kun testtider. Fly er ikke bekreftet og bestilles separat. Tidene er lokale for hver flyplass.','Flysøk blir tilgjengelig når testforbindelsen er konfigurert.','Flysøk krever kjente flyplasser, datoer og høyst ni voksne uten barn. En konsulent kan hjelpe med detaljene.','Ingen passende testfly ble funnet for reisens datoer og flyplasser. Konsulenten kan gjennomgå ruten.','Foreslått flyreiseplan','Ingen flyreiseplan valgt'],
fr:['Vols pour votre voyage','Horaires de test uniquement. Les vols ne sont pas confirmés et doivent être réservés séparément. Les heures sont locales.','La recherche sera disponible une fois notre connexion de test configurée.','La recherche nécessite des aéroports reconnus, des dates et un groupe de neuf adultes maximum sans enfants. Un conseiller peut préciser les détails.','Aucun vol de test adapté aux dates et aux aéroports. Votre conseiller peut revoir le trajet.','Itinéraire suggéré','Aucun itinéraire aérien sélectionné'],
es:['Vuelos para tu viaje','Solo horarios de prueba. Los vuelos no están confirmados y se reservan por separado. Las horas son locales.','La búsqueda estará disponible cuando se configure nuestra conexión de prueba.','La búsqueda requiere aeropuertos reconocidos, fechas y hasta nueve adultos sin niños. Un asesor puede aclarar los detalles.','No se encontraron vuelos de prueba adecuados para las fechas y los aeropuertos. Tu asesor puede revisar la ruta.','Itinerario sugerido','Ningún itinerario de vuelos seleccionado'],
it:['Voli per il tuo viaggio','Solo orari di prova. I voli non sono confermati e vanno prenotati separatamente. Gli orari sono locali.','La ricerca sarà disponibile dopo la configurazione della connessione di prova.','La ricerca richiede aeroporti riconosciuti, date e fino a nove adulti senza bambini. Un consulente può chiarire i dettagli.','Nessun volo di prova adatto alle date e agli aeroporti. Il consulente può rivedere il percorso.','Itinerario suggerito','Nessun itinerario dei voli selezionato'],
nl:['Vluchten voor je reis','Alleen testtijden. Vluchten zijn niet bevestigd en worden afzonderlijk geboekt. De tijden zijn lokaal.','Zoeken wordt beschikbaar zodra onze testverbinding is ingesteld.','Zoeken vereist bekende luchthavens, datums en maximaal negen volwassenen zonder kinderen. Een adviseur kan de details verduidelijken.','Geen passende testvluchten gevonden voor de datums en luchthavens. Je adviseur kan de route bekijken.','Voorgesteld vluchtschema','Geen vluchtschema geselecteerd'],
hu:['Repülőjáratok az utazáshoz','Csak tesztmenetrend. A járatok nem megerősítettek, külön foglalhatók. Az időpontok helyi idők.','A keresés a tesztkapcsolat beállítása után lesz elérhető.','A keresés ismert repülőtereket, dátumokat és legfeljebb kilenc felnőttet igényel, gyermekek nélkül. A tanácsadó segíthet pontosítani.','Nem találtunk megfelelő tesztjáratokat a dátumokra és repülőterekre. A tanácsadó átnézheti az útvonalat.','Javasolt repülési útiterv','Nincs kiválasztott repülési útiterv']};
export default function PlannerFlights({plan,locale,selected,onSelect}:{plan:FlightPlan;locale:string;selected?:FlightItinerary;onSelect:(flight?:FlightItinerary)=>void}){
 const c=copy[locale]||copy.en;
 return <section className="traveller-research planner-flights"><h3>{c[0]}</h3><p>{c[1]}</p>{plan.status!=='test-results'?<p>{c[plan.status==='not-connected'?2:plan.status==='needs-details'?3:4]}</p>:<><div className="hotel-options">{plan.offers.map((f,i)=><label className="hotel-option" key={f.offerId}><input type="radio" name="planner-flight" checked={selected?.offerId===f.offerId} onChange={()=>onSelect(f)}/><div><strong>{c[5]} {i+1}</strong>{f.slices.map((slice,j)=><div key={j}>{slice.map((s,k)=><p key={k}><b>{s.origin} → {s.destination}</b><br/>{s.airline} · {s.flightNumber}<br/>{s.departure.replace('T',' ')} → {s.arrival.replace('T',' ')}</p>)}</div>)}</div></label>)}</div><label><input type="radio" name="planner-flight" checked={!selected} onChange={()=>onSelect()}/>{c[6]}</label></>}</section>;
}
