import {liveFlightNote,flightTable} from '../../functions/_lib/flight-display';
import type {PlannerFlights as FlightPlan} from '../../functions/_lib/planner-flights';
import type {FlightItinerary} from '../../functions/_lib/duffel';
const copy:Record<string,string[]>={
en:["Flights for your journey", "Test schedules only. Flights are not confirmed and must be arranged separately. Times are local to each airport.", "Flight search is currently unavailable. Your consultant can help.", "Provide recognised airports, travel dates and passenger ages. Searches support up to nine travellers; infants require consultant review.", "No suitable flights were returned for the journey dates and airports. Your consultant can review the routing.", "Suggested itinerary", "No flight itinerary selected"],
da:["Fly til din rejse", "Kun testtider. Fly er ikke bekræftet og bestilles separat. Tiderne er lokale for hver lufthavn.", "Flysøgning er ikke tilgængelig lige nu. Din konsulent kan hjælpe.", "Angiv kendte lufthavne, rejsedatoer og passagerernes alder. Søgning understøtter op til ni rejsende; spædbørn kræver konsulentens hjælp.", "Der blev ikke fundet passende fly til rejsens datoer og lufthavne. Din konsulent kan gennemgå ruten.", "Foreslået flyrejseplan", "Ingen flyrejseplan valgt"],
sv:["Flyg för din resa", "Endast testtider. Flygen är inte bekräftade och bokas separat. Tiderna är lokala för varje flygplats.", "Flygsökning är inte tillgänglig just nu. Din konsult kan hjälpa.", "Ange kända flygplatser, resedatum och passagerarnas ålder. Sökning stöder upp till nio resenärer; spädbarn kräver konsultens hjälp.", "Inga lämpliga testflyg hittades för resans datum och flygplatser. Din konsult kan granska rutten.", "Föreslagen flygresplan", "Ingen flygresplan vald"],
no:["Fly til reisen din", "Kun testtider. Fly er ikke bekreftet og bestilles separat. Tidene er lokale for hver flyplass.", "Flysøk er ikke tilgjengelig akkurat nå. Konsulenten din kan hjelpe.", "Oppgi kjente flyplasser, reisedatoer og passasjerenes alder. Søk støtter opptil ni reisende; spedbarn krever hjelp fra konsulenten.", "Ingen passende fly ble funnet for reisens datoer og flyplasser. Konsulenten kan gjennomgå ruten.", "Foreslått flyreiseplan", "Ingen flyreiseplan valgt"],
fr:["Vols pour votre voyage", "Horaires de test uniquement. Les vols ne sont pas confirmés et doivent être réservés séparément. Les heures sont locales.", "La recherche de vols est indisponible actuellement. Votre conseiller peut vous aider.", "Indiquez les aéroports, les dates et l’âge des passagers. Jusqu’à neuf voyageurs sont pris en charge ; les nourrissons nécessitent l’aide du conseiller.", "Aucun vol adapté aux dates et aux aéroports. Votre conseiller peut revoir le trajet.", "Itinéraire suggéré", "Aucun itinéraire aérien sélectionné"],
es:["Vuelos para tu viaje", "Solo horarios de prueba. Los vuelos no están confirmados y se reservan por separado. Las horas son locales.", "La búsqueda de vuelos no está disponible ahora. Tu asesor puede ayudarte.", "Indica aeropuertos, fechas y edades. Se admiten hasta nueve viajeros; los bebés requieren la revisión del asesor.", "No se encontraron vuelos adecuados para las fechas y los aeropuertos. Tu asesor puede revisar la ruta.", "Itinerario sugerido", "Ningún itinerario de vuelos seleccionado"],
it:["Voli per il tuo viaggio", "Solo orari di prova. I voli non sono confermati e vanno prenotati separatamente. Gli orari sono locali.", "La ricerca voli non è disponibile al momento. Il consulente può aiutarti.", "Indica aeroporti, date ed età dei passeggeri. Sono supportati fino a nove viaggiatori; per i neonati serve il consulente.", "Nessun volo adatto alle date e agli aeroporti. Il consulente può rivedere il percorso.", "Itinerario suggerito", "Nessun itinerario dei voli selezionato"],
nl:["Vluchten voor je reis", "Alleen testtijden. Vluchten zijn niet bevestigd en worden afzonderlijk geboekt. De tijden zijn lokaal.", "Vluchten zoeken is momenteel niet beschikbaar. Je adviseur kan helpen.", "Vul luchthavens, reisdatums en leeftijden in. Zoeken ondersteunt maximaal negen reizigers; baby’s vereisen beoordeling door de adviseur.", "Geen passende vluchten gevonden voor de datums en luchthavens. Je adviseur kan de route bekijken.", "Voorgesteld vluchtschema", "Geen vluchtschema geselecteerd"],
hu:["Repülőjáratok az utazáshoz", "Csak tesztmenetrend. A járatok nem megerősítettek, külön foglalhatók. Az időpontok helyi idők.", "A járatkeresés jelenleg nem érhető el. Tanácsadója segíthet.", "Adja meg a repülőtereket, az utazási dátumokat és az utasok életkorát. Legfeljebb kilenc utas kereshető; csecsemők esetén tanácsadói segítség szükséges.", "Nem találtunk megfelelő járatokat a dátumokra és repülőterekre. A tanácsadó átnézheti az útvonalat.", "Javasolt repülési útiterv", "Nincs kiválasztott repülési útiterv"]};
const detailCopy:Record<string,string[]>={
en:["Details needed", "Departure airport", "Arrival airport", "Return airport", "Travel dates", "Passenger count and child ages", "Ground transfer needed between", "and airport"],
da:["Nødvendige oplysninger", "Afrejselufthavn", "Ankomstlufthavn", "Hjemrejselufthavn", "Rejsedatoer", "Antal passagerer og børnenes alder", "Landtransport nødvendig mellem", "og lufthavn"],
sv:["Uppgifter som behövs", "Avreseflygplats", "Ankomstflygplats", "Hemreseflygplats", "Resedatum", "Antal passagerare och barnens ålder", "Marktransport behövs mellan", "och flygplats"],
no:["Opplysninger som trengs", "Avreiseflyplass", "Ankomstflyplass", "Returflyplass", "Reisedatoer", "Antall passasjerer og barnas alder", "Bakketransport trengs mellom", "og flyplass"],
fr:["Informations nécessaires", "Aéroport de départ", "Aéroport d’arrivée", "Aéroport de retour", "Dates du voyage", "Nombre de passagers et âge des enfants", "Transfert terrestre nécessaire entre", "et l’aéroport"],
es:["Datos necesarios", "Aeropuerto de salida", "Aeropuerto de llegada", "Aeropuerto de regreso", "Fechas del viaje", "Número de pasajeros y edades de los niños", "Se necesita traslado terrestre entre", "y el aeropuerto"],
it:["Dati necessari", "Aeroporto di partenza", "Aeroporto di arrivo", "Aeroporto di ritorno", "Date del viaggio", "Numero di passeggeri ed età dei bambini", "Trasferimento terrestre necessario tra", "e l’aeroporto"],
nl:["Benodigde gegevens", "Vertrekluchthaven", "Aankomstluchthaven", "Luchthaven voor terugreis", "Reisdatums", "Aantal reizigers en leeftijden van kinderen", "Vervoer over land nodig tussen", "en luchthaven"],
hu:["Szükséges adatok", "Indulási repülőtér", "Érkezési repülőtér", "Visszaúti repülőtér", "Utazási dátumok", "Utasok száma és gyermekek életkora", "Szárazföldi transzfer szükséges:", "és repülőtér"]};
export default function PlannerFlights({plan,locale,selected,onSelect,step}:{step?:string;plan:FlightPlan;locale:string;selected?:FlightItinerary;onSelect:(flight?:FlightItinerary)=>void}){
 const c=copy[locale]||copy.en,d=detailCopy[locale]||detailCopy.en;const live=plan.status==='search-results';
 return <section className="traveller-research planner-flights"><link rel="stylesheet" href="/flights.css"/><div className="section-heading">{step&&<span>{step}</span>}<h3>{c[0]}</h3></div>{(live||plan.provider!=='serpapi')&&<p>{live?liveFlightNote(locale):c[1]}</p>}{plan.status!=='test-results'&&plan.status!=='search-results'?<div><p>{c[plan.status==='not-connected'?2:plan.status==='needs-details'?3:4]}</p>{plan.issues?.length&&<p>{d[0]}: {plan.issues.map(issue=>d[['departure','arrival','return','dates','party'].indexOf(issue)+1]).join(' · ')}</p>}</div>:<><div className="hotel-options">{plan.offers.map((f,i)=><label className="hotel-option" key={f.offerId}><input type="radio" name="planner-flight" checked={selected?.offerId===f.offerId} onChange={()=>onSelect(f)}/><div><strong>{c[5]} {i+1}</strong><div dangerouslySetInnerHTML={{__html:flightTable(f,locale)}}/></div></label>)}</div><label><input type="radio" name="planner-flight" checked={!selected} onChange={()=>onSelect()}/>{c[6]}</label></>}</section>;
}
