import {useState} from 'react';

export default function TourGallery({images,name,variant='card'}:{images:string[];name:string;variant?:'card'|'feature'}){
  const unique=[...new Set(images)].slice(0,4);
  const [current,setCurrent]=useState(0);
  const move=(step:number)=>setCurrent(index=>(index+step+unique.length)%unique.length);
  return <div className={`tour-gallery gallery-${variant}`} aria-label={`${name} image gallery`}>
    <div className="main-image"><img src={unique[current]} alt={`${name} travel scene ${current+1}`} loading={variant==='card'?'lazy':'eager'}/><button className="previous" type="button" onClick={()=>move(-1)} aria-label={`Previous ${name} image`}>←</button><button className="next" type="button" onClick={()=>move(1)} aria-label={`Next ${name} image`}>→</button><span>{String(current+1).padStart(2,'0')} / {String(unique.length).padStart(2,'0')}</span></div>
    <div className="thumbnails">{unique.map((src,index)=><button type="button" className={index===current?'active':''} onClick={()=>setCurrent(index)} aria-label={`Show ${name} image ${index+1}`} aria-pressed={index===current} key={src}><img src={src} alt="" loading="lazy"/></button>)}</div>
    <style>{`.tour-gallery{background:#10271f}.main-image{position:relative;overflow:hidden}.main-image>img{width:100%;height:100%;object-fit:cover;transition:opacity .2s}.gallery-card .main-image{aspect-ratio:4/3}.gallery-feature .main-image{aspect-ratio:16/8}.main-image button{position:absolute;top:50%;transform:translateY(-50%);width:2.35rem;height:2.35rem;border:1px solid rgba(255,255,255,.7);border-radius:50%;background:rgba(6,25,19,.62);color:#fff;font-size:1rem;display:grid;place-items:center}.main-image button:hover,.main-image button:focus-visible{background:#10271f;border-color:#fff}.previous{left:.65rem}.next{right:.65rem}.main-image>span{position:absolute;right:.65rem;bottom:.6rem;padding:.25rem .45rem;background:rgba(6,25,19,.72);color:#fff;font:500 .5rem var(--mono);letter-spacing:.08em}.thumbnails{display:grid;grid-template-columns:repeat(4,1fr);gap:3px;padding-top:3px}.thumbnails button{height:58px;padding:0;border:2px solid transparent;background:#10271f;opacity:.72;overflow:hidden}.gallery-feature .thumbnails button{height:110px}.thumbnails button.active{border-color:var(--vermilion);opacity:1}.thumbnails img{width:100%;height:100%;object-fit:cover}.gallery-feature{max-width:1180px;margin:auto}@media(max-width:700px){.gallery-feature .main-image{aspect-ratio:4/3}.gallery-feature .thumbnails button{height:68px}.main-image button{width:2rem;height:2rem}}`}</style>
  </div>
}
