import {useMemo,useState,type SyntheticEvent} from 'react';
import type {TripSuggestion} from '../lib/tripPlanner';
import HbxAvailability from './HbxAvailability';

type Locale = 'en'|'es'|'it'|'fr'|'nl'|'hu'|'sv'|'da'|'no';

const copy:Record<Locale,Record<string,string>>={
  en:{start:'Your trip, in outline',intro:'Tell the agent what matters. It can design a tailor-made route anywhere in Asia; Way to Asia journeys are optional inspiration, not a limit.',where:'Where would you like to go?',open:'Open to ideas',when:'When?',flexible:'Dates flexible',days:'Days',travellers:'Travellers',adults:'Adults',children:'Children',budget:'Comfort level',value:'Thoughtful value',comfort:'Comfort',premium:'Premium',luxury:'Luxury',unsure:'Not sure yet',pace:'Pace',slow:'Slow and immersive',balanced:'Balanced',active:'Active and full',interests:'What should shape the journey?',food:'Food & local culture',history:'History & heritage',nature:'Nature & wildlife',art:'Art & design',wellness:'Wellness & relaxation',family:'Family time',celebration:'Honeymoon or celebration',notes:'Anything the agent should know?',placeholder:'Previous trips, mobility needs, must-see places, celebrations…',submit:'Create my trip idea',working:'Composing your route…',notice:'Ideas only · No live availability or confirmed prices yet',error:'Please choose at least one interest.',route:'Suggested flow',fit:'Why it fits',notesTitle:'Keep in mind',matches:'Way to Asia journeys to explore',daysLabel:'days',from:'Illustrative from',refine:'Refine the idea',contact:'Discuss with a travel designer',newIdea:'Start a new idea'},
  da:{start:'Din rejse i hovedtræk',intro:'Fortæl agenten, hvad der betyder mest. Den kan skabe en skræddersyet rute overalt i Asien; Way to Asia-rejser er inspiration, ikke en begrænsning.',where:'Hvor vil du gerne rejse?',open:'Åben for idéer',when:'Hvornår?',flexible:'Fleksible datoer',days:'Dage',travellers:'Rejsende',adults:'Voksne',children:'Børn',budget:'Komfortniveau',value:'God værdi',comfort:'Komfort',premium:'Premium',luxury:'Luksus',unsure:'Ikke sikker endnu',pace:'Tempo',slow:'Langsomt og fordybende',balanced:'Afbalanceret',active:'Aktivt og oplevelsesrigt',interests:'Hvad skal forme rejsen?',food:'Mad og lokal kultur',history:'Historie og kulturarv',nature:'Natur og dyreliv',art:'Kunst og design',wellness:'Velvære og afslapning',family:'Familietid',celebration:'Bryllupsrejse eller fejring',notes:'Er der andet, agenten skal vide?',placeholder:'Tidligere rejser, mobilitetsbehov, steder I vil se, fejringer…',submit:'Skab mit rejseforslag',working:'Sammensætter din rute…',notice:'Kun idéer · Endnu ingen live-tilgængelighed eller bekræftede priser',error:'Vælg mindst én interesse.',route:'Foreslået rejseforløb',fit:'Derfor passer det',notesTitle:'Vær opmærksom på',matches:'Way to Asia-rejser at udforske',daysLabel:'dage',from:'Vejledende fra',refine:'Tilpas idéen',contact:'Tal med en rejsekonsulent',newIdea:'Start en ny idé'},
  es:{start:'Tu viaje, en líneas generales',intro:'Cuéntale al agente qué es importante. Creará una primera ruta con el conocimiento de Way to Asia, sin consultar inventario en directo.',where:'¿Adónde te gustaría ir?',open:'Abierto a ideas',when:'¿Cuándo?',flexible:'Fechas flexibles',days:'Días',travellers:'Viajeros',adults:'Adultos',children:'Niños',budget:'Nivel de confort',value:'Buena relación calidad-precio',comfort:'Confort',premium:'Premium',luxury:'Lujo',unsure:'Aún no lo sé',pace:'Ritmo',slow:'Lento e inmersivo',balanced:'Equilibrado',active:'Activo e intenso',interests:'¿Qué debe definir el viaje?',food:'Gastronomía y cultura local',history:'Historia y patrimonio',nature:'Naturaleza y fauna',art:'Arte y diseño',wellness:'Bienestar y descanso',family:'Tiempo en familia',celebration:'Luna de miel o celebración',notes:'¿Algo más que deba saber el agente?',placeholder:'Viajes anteriores, movilidad, lugares imprescindibles, celebraciones…',submit:'Crear mi idea de viaje',working:'Componiendo tu ruta…',notice:'Solo ideas · Aún sin disponibilidad ni precios confirmados',error:'Elige al menos un interés.',route:'Ruta sugerida',fit:'Por qué encaja',notesTitle:'A tener en cuenta',matches:'Viajes de Way to Asia para explorar',daysLabel:'días',from:'Desde, de forma orientativa',refine:'Ajustar la idea',contact:'Hablar con un diseñador de viajes',newIdea:'Crear otra idea'},
  it:{start:'Il tuo viaggio, in sintesi',intro:'Racconta all’agente cosa conta per te. Creerà una prima rotta dalla conoscenza di Way to Asia, senza cercare disponibilità live.',where:'Dove vorresti andare?',open:'Aperto a proposte',when:'Quando?',flexible:'Date flessibili',days:'Giorni',travellers:'Viaggiatori',adults:'Adulti',children:'Bambini',budget:'Livello di comfort',value:'Valore curato',comfort:'Comfort',premium:'Premium',luxury:'Lusso',unsure:'Non ancora sicuro',pace:'Ritmo',slow:'Lento e immersivo',balanced:'Equilibrato',active:'Attivo e intenso',interests:'Cosa deve dare forma al viaggio?',food:'Cibo e cultura locale',history:'Storia e patrimonio',nature:'Natura e fauna',art:'Arte e design',wellness:'Benessere e relax',family:'Tempo in famiglia',celebration:'Luna di miele o celebrazione',notes:'Cos’altro dovrebbe sapere l’agente?',placeholder:'Viaggi precedenti, mobilità, luoghi imperdibili, celebrazioni…',submit:'Crea la mia idea di viaggio',working:'Stiamo componendo il tuo itinerario…',notice:'Solo idee · Disponibilità e prezzi non sono ancora confermati',error:'Scegli almeno un interesse.',route:'Percorso suggerito',fit:'Perché fa per te',notesTitle:'Da tenere presente',matches:'Viaggi Way to Asia da esplorare',daysLabel:'giorni',from:'Indicativamente da',refine:'Perfeziona l’idea',contact:'Parla con un travel designer',newIdea:'Crea una nuova idea'},
  fr:{start:'Votre voyage, dans les grandes lignes',intro:'Indiquez à l’agent ce qui compte. Il dessinera un premier itinéraire à partir du savoir de Way to Asia, sans interroger les stocks en direct.',where:'Où souhaitez-vous aller ?',open:'Ouvert aux idées',when:'Quand ?',flexible:'Dates flexibles',days:'Jours',travellers:'Voyageurs',adults:'Adultes',children:'Enfants',budget:'Niveau de confort',value:'Valeur soignée',comfort:'Confort',premium:'Premium',luxury:'Luxe',unsure:'Pas encore décidé',pace:'Rythme',slow:'Lent et immersif',balanced:'Équilibré',active:'Actif et soutenu',interests:'Qu’est-ce qui doit façonner le voyage ?',food:'Cuisine et culture locale',history:'Histoire et patrimoine',nature:'Nature et faune',art:'Art et design',wellness:'Bien-être et détente',family:'Temps en famille',celebration:'Lune de miel ou célébration',notes:'Autre chose à signaler à l’agent ?',placeholder:'Voyages précédents, mobilité, lieux incontournables, célébrations…',submit:'Créer mon idée de voyage',working:'Composition de votre itinéraire…',notice:'Idées uniquement · Pas encore de disponibilité ni de prix confirmés',error:'Choisissez au moins un centre d’intérêt.',route:'Parcours suggéré',fit:'Pourquoi il vous correspond',notesTitle:'À garder en tête',matches:'Voyages Way to Asia à découvrir',daysLabel:'jours',from:'À titre indicatif, à partir de',refine:'Affiner l’idée',contact:'Échanger avec un créateur de voyages',newIdea:'Créer une autre idée'},
  nl:{start:'Je reis in hoofdlijnen',intro:'Vertel de agent wat belangrijk is. Die maakt een eerste route met de kennis van Way to Asia, zonder live aanbod te doorzoeken.',where:'Waar wil je naartoe?',open:'Open voor ideeën',when:'Wanneer?',flexible:'Flexibele data',days:'Dagen',travellers:'Reizigers',adults:'Volwassenen',children:'Kinderen',budget:'Comfortniveau',value:'Bewuste waarde',comfort:'Comfort',premium:'Premium',luxury:'Luxe',unsure:'Nog niet zeker',pace:'Tempo',slow:'Rustig en verdiepend',balanced:'Gebalanceerd',active:'Actief en vol',interests:'Wat moet de reis bepalen?',food:'Eten en lokale cultuur',history:'Geschiedenis en erfgoed',nature:'Natuur en dieren',art:'Kunst en design',wellness:'Welzijn en ontspanning',family:'Tijd met het gezin',celebration:'Huwelijksreis of viering',notes:'Wat moet de agent nog weten?',placeholder:'Eerdere reizen, mobiliteit, plekken die je wilt zien, vieringen…',submit:'Maak mijn reisidee',working:'Je route wordt samengesteld…',notice:'Alleen ideeën · Nog geen live beschikbaarheid of bevestigde prijzen',error:'Kies minstens één interesse.',route:'Voorgestelde route',fit:'Waarom dit past',notesTitle:'Goed om te weten',matches:'Way to Asia-reizen om te bekijken',daysLabel:'dagen',from:'Indicatief vanaf',refine:'Verfijn het idee',contact:'Bespreek het met een reisontwerper',newIdea:'Start een nieuw idee'},
  hu:{start:'Az utazás fő vonalai',intro:'Mondja el az ügynöknek, mi fontos. A Way to Asia tudásából készít első útvonalat, élő készletkeresés nélkül.',where:'Hová utazna?',open:'Nyitott vagyok ötletekre',when:'Mikor?',flexible:'Rugalmas időpont',days:'Nap',travellers:'Utazók',adults:'Felnőttek',children:'Gyerekek',budget:'Komfortszint',value:'Átgondolt érték',comfort:'Kényelmes',premium:'Prémium',luxury:'Luxus',unsure:'Még nem tudom',pace:'Tempó',slow:'Lassú és elmélyült',balanced:'Kiegyensúlyozott',active:'Aktív és tartalmas',interests:'Mi formálja az utazást?',food:'Ételek és helyi kultúra',history:'Történelem és örökség',nature:'Természet és vadvilág',art:'Művészet és design',wellness:'Wellness és pihenés',family:'Családi idő',celebration:'Nászút vagy ünneplés',notes:'Mit tudjon még az ügynök?',placeholder:'Korábbi utak, mobilitási igények, kihagyhatatlan helyek, ünneplés…',submit:'Kérem az utazási ötletem',working:'Az útvonal összeállítása…',notice:'Csak ötlet · Még nincs élő elérhetőség vagy megerősített ár',error:'Válasszon legalább egy érdeklődési kört.',route:'Javasolt útvonal',fit:'Miért illik Önhöz',notesTitle:'Fontos tudnivalók',matches:'Felfedezhető Way to Asia utak',daysLabel:'nap',from:'Tájékoztató ár ettől',refine:'Ötlet finomítása',contact:'Beszéljen utazástervezővel',newIdea:'Új ötlet indítása'},
  sv:{start:'Din resa i stora drag',intro:'Berätta för agenten vad som är viktigt. Den skapar ett första ruttförslag från Way to Asias kunskap utan att söka liveutbud.',where:'Vart vill du resa?',open:'Öppen för idéer',when:'När?',flexible:'Flexibla datum',days:'Dagar',travellers:'Resenärer',adults:'Vuxna',children:'Barn',budget:'Komfortnivå',value:'Genomtänkt värde',comfort:'Komfort',premium:'Premium',luxury:'Lyx',unsure:'Inte säker än',pace:'Tempo',slow:'Långsamt och fördjupande',balanced:'Balanserat',active:'Aktivt och innehållsrikt',interests:'Vad ska forma resan?',food:'Mat och lokal kultur',history:'Historia och kulturarv',nature:'Natur och djurliv',art:'Konst och design',wellness:'Välmående och avkoppling',family:'Familjetid',celebration:'Smekmånad eller firande',notes:'Något mer agenten bör veta?',placeholder:'Tidigare resor, tillgänglighetsbehov, måsten, firanden…',submit:'Skapa mitt reseförslag',working:'Sätter samman din rutt…',notice:'Endast idéer · Ingen live-tillgänglighet eller bekräftade priser ännu',error:'Välj minst ett intresse.',route:'Föreslagen rutt',fit:'Därför passar den',notesTitle:'Bra att tänka på',matches:'Way to Asia-resor att utforska',daysLabel:'dagar',from:'Vägledande från',refine:'Förfina idén',contact:'Prata med en resedesigner',newIdea:'Starta en ny idé'},
  no:{start:'Reisen din i hovedtrekk',intro:'Fortell agenten hva som betyr mest. Den lager et første ruteforslag fra Way to Asias kunnskap, uten å søke i live leverandørutvalg.',where:'Hvor vil du reise?',open:'Åpen for ideer',when:'Når?',flexible:'Fleksible datoer',days:'Dager',travellers:'Reisende',adults:'Voksne',children:'Barn',budget:'Komfortnivå',value:'God verdi',comfort:'Komfort',premium:'Premium',luxury:'Luksus',unsure:'Ikke sikker ennå',pace:'Tempo',slow:'Langsomt og fordypende',balanced:'Balansert',active:'Aktivt og innholdsrikt',interests:'Hva skal forme reisen?',food:'Mat og lokal kultur',history:'Historie og kulturarv',nature:'Natur og dyreliv',art:'Kunst og design',wellness:'Velvære og avslapning',family:'Familietid',celebration:'Bryllupsreise eller feiring',notes:'Noe mer agenten bør vite?',placeholder:'Tidligere reiser, behov for tilrettelegging, steder dere må se, feiringer…',submit:'Lag reiseforslaget mitt',working:'Setter sammen ruten din…',notice:'Kun ideer · Ingen live-tilgjengelighet eller bekreftede priser ennå',error:'Velg minst én interesse.',route:'Foreslått reise',fit:'Derfor passer den',notesTitle:'Verdt å vite',matches:'Way to Asia-reiser å utforske',daysLabel:'dager',from:'Veiledende fra',refine:'Tilpass ideen',contact:'Snakk med en reisedesigner',newIdea:'Start en ny idé'},
};

const agentCopy:Record<Locale,{anywhere:string;destinationIdeas:string;destinationPlaceholder:string;refineTitle:string;refineIntro:string;refinePlaceholder:string;refineSubmit:string;refining:string;tailorMade:string;inputError:string;capacityError:string}>={
  en:{anywhere:'Anywhere in Asia',destinationIdeas:'Destinations or regions — anywhere in Asia',destinationPlaceholder:'For example: Japan and Taiwan, rural Laos, or choose for me…',refineTitle:'Refine this journey with the agent',refineIntro:'Ask for a slower pace, a different country, fewer flights, more nature, or any other change. The agent will rebuild the complete route.',refinePlaceholder:'For example: Replace the final city with three quiet beach days and reduce internal flights.',refineSubmit:'Revise my journey',refining:'Reworking your route…',tailorMade:'Tailor-made beyond the catalogue',inputError:'Choose an interest or describe the journey you want.',capacityError:'The AI service has reached today’s allowance. Please try again after the daily reset.'},
  da:{anywhere:'Hvor som helst i Asien',destinationIdeas:'Destinationer eller regioner – hvor som helst i Asien',destinationPlaceholder:'For eksempel Japan og Taiwan, Laos på landet eller vælg for mig…',refineTitle:'Tilpas rejsen sammen med agenten',refineIntro:'Bed om et roligere tempo, et andet land, færre fly, mere natur eller en anden ændring. Agenten bygger hele ruten om.',refinePlaceholder:'For eksempel: Erstat den sidste by med tre rolige stranddage og færre indenrigsfly.',refineSubmit:'Tilpas min rejse',refining:'Tilpasser din rute…',tailorMade:'Skræddersyet ud over kataloget',inputError:'Vælg en interesse eller beskriv den rejse, du ønsker.',capacityError:'AI-tjenesten har nået dagens grænse. Prøv igen efter den daglige nulstilling.'},
  es:{anywhere:'Cualquier lugar de Asia',destinationIdeas:'Destinos o regiones — en cualquier lugar de Asia',destinationPlaceholder:'Por ejemplo: Japón y Taiwán, Laos rural o elige por mí…',refineTitle:'Perfecciona este viaje con el agente',refineIntro:'Pide un ritmo más lento, otro país, menos vuelos, más naturaleza o cualquier cambio. El agente reconstruirá la ruta completa.',refinePlaceholder:'Por ejemplo: sustituye la última ciudad por tres días tranquilos de playa y reduce los vuelos internos.',refineSubmit:'Revisar mi viaje',refining:'Rehaciendo tu ruta…',tailorMade:'A medida, más allá del catálogo',inputError:'Elige un interés o describe el viaje que deseas.',capacityError:'El servicio de IA ha alcanzado el límite de hoy. Inténtalo de nuevo después del reinicio diario.'},
  it:{anywhere:'Ovunque in Asia',destinationIdeas:'Destinazioni o regioni — ovunque in Asia',destinationPlaceholder:'Per esempio: Giappone e Taiwan, Laos rurale oppure scegli tu…',refineTitle:'Perfeziona il viaggio con l’agente',refineIntro:'Chiedi un ritmo più lento, un altro paese, meno voli, più natura o qualsiasi modifica. L’agente ricostruirà l’intero itinerario.',refinePlaceholder:'Per esempio: sostituisci l’ultima città con tre giorni tranquilli al mare e riduci i voli interni.',refineSubmit:'Rivedi il mio viaggio',refining:'Rielaborazione del percorso…',tailorMade:'Su misura oltre il catalogo',inputError:'Scegli un interesse o descrivi il viaggio che desideri.',capacityError:'Il servizio IA ha raggiunto il limite giornaliero. Riprova dopo il ripristino quotidiano.'},
  fr:{anywhere:'Partout en Asie',destinationIdeas:'Destinations ou régions — partout en Asie',destinationPlaceholder:'Par exemple : Japon et Taïwan, Laos rural, ou choisissez pour moi…',refineTitle:'Affinez ce voyage avec l’agent',refineIntro:'Demandez un rythme plus lent, un autre pays, moins de vols, plus de nature ou tout autre changement. L’agent reconstruira l’itinéraire complet.',refinePlaceholder:'Par exemple : remplacez la dernière ville par trois jours tranquilles à la plage et réduisez les vols intérieurs.',refineSubmit:'Revoir mon voyage',refining:'Révision de votre itinéraire…',tailorMade:'Sur mesure au-delà du catalogue',inputError:'Choisissez un intérêt ou décrivez le voyage souhaité.',capacityError:'Le service d’IA a atteint la limite du jour. Réessayez après la réinitialisation quotidienne.'},
  nl:{anywhere:'Overal in Azië',destinationIdeas:'Bestemmingen of regio’s — overal in Azië',destinationPlaceholder:'Bijvoorbeeld: Japan en Taiwan, landelijk Laos, of kies voor mij…',refineTitle:'Verfijn deze reis met de agent',refineIntro:'Vraag om een rustiger tempo, een ander land, minder vluchten, meer natuur of een andere wijziging. De agent bouwt de volledige route opnieuw op.',refinePlaceholder:'Bijvoorbeeld: vervang de laatste stad door drie rustige stranddagen en verminder binnenlandse vluchten.',refineSubmit:'Mijn reis aanpassen',refining:'Je route wordt aangepast…',tailorMade:'Maatwerk buiten de catalogus',inputError:'Kies een interesse of beschrijf de reis die je wilt.',capacityError:'De AI-dienst heeft de daglimiet bereikt. Probeer het opnieuw na de dagelijkse reset.'},
  hu:{anywhere:'Bárhol Ázsiában',destinationIdeas:'Úti célok vagy régiók — bárhol Ázsiában',destinationPlaceholder:'Például Japán és Tajvan, vidéki Laosz, vagy válasszon helyettem…',refineTitle:'Finomítsa az utat az ügynökkel',refineIntro:'Kérjen lassabb tempót, másik országot, kevesebb repülést, több természetet vagy bármilyen változtatást. Az ügynök újratervezi a teljes útvonalat.',refinePlaceholder:'Például: az utolsó város helyett legyen három nyugodt tengerparti nap, kevesebb belföldi repüléssel.',refineSubmit:'Utazás módosítása',refining:'Az útvonal átdolgozása…',tailorMade:'Katalóguson túli, személyre szabott út',inputError:'Válasszon érdeklődési kört, vagy írja le a kívánt utazást.',capacityError:'Az AI-szolgáltatás elérte a mai keretet. Próbálja újra a napi visszaállítás után.'},
  sv:{anywhere:'Var som helst i Asien',destinationIdeas:'Resmål eller regioner — var som helst i Asien',destinationPlaceholder:'Till exempel Japan och Taiwan, landsbygden i Laos eller välj åt mig…',refineTitle:'Förfina resan med agenten',refineIntro:'Be om lugnare tempo, ett annat land, färre flyg, mer natur eller någon annan ändring. Agenten bygger om hela rutten.',refinePlaceholder:'Till exempel: byt den sista staden mot tre lugna stranddagar och minska inrikesflygen.',refineSubmit:'Ändra min resa',refining:'Arbetar om din rutt…',tailorMade:'Skräddarsytt utanför katalogen',inputError:'Välj ett intresse eller beskriv resan du vill ha.',capacityError:'AI-tjänsten har nått dagens gräns. Försök igen efter den dagliga återställningen.'},
  no:{anywhere:'Hvor som helst i Asia',destinationIdeas:'Reisemål eller regioner — hvor som helst i Asia',destinationPlaceholder:'For eksempel Japan og Taiwan, landsbygda i Laos eller velg for meg…',refineTitle:'Tilpass reisen med agenten',refineIntro:'Be om roligere tempo, et annet land, færre fly, mer natur eller en annen endring. Agenten bygger hele ruten på nytt.',refinePlaceholder:'For eksempel: Bytt den siste byen med tre rolige stranddager og reduser innenriksfly.',refineSubmit:'Tilpass reisen min',refining:'Arbeider om ruten din…',tailorMade:'Skreddersydd utover katalogen',inputError:'Velg en interesse eller beskriv reisen du ønsker.',capacityError:'AI-tjenesten har nådd dagens grense. Prøv igjen etter den daglige tilbakestillingen.'},
};

const agentIntro:Record<Locale,string>={
  en:'Tell the agent what matters. It can design a tailor-made route anywhere in Asia; Way to Asia journeys are optional inspiration, not a limit.',
  da:'Fortæl agenten, hvad der betyder mest. Den kan skabe en skræddersyet rute overalt i Asien; Way to Asia-rejser er inspiration, ikke en begrænsning.',
  es:'Cuéntale al agente qué es importante. Puede diseñar una ruta a medida por cualquier lugar de Asia; los viajes de Way to Asia son inspiración, no un límite.',
  it:'Racconta all’agente cosa conta per te. Può creare un itinerario su misura ovunque in Asia; i viaggi Way to Asia sono ispirazione, non un limite.',
  fr:'Indiquez à l’agent ce qui compte. Il peut créer un itinéraire sur mesure partout en Asie ; les voyages Way to Asia sont une inspiration, pas une limite.',
  nl:'Vertel de agent wat belangrijk is. Die kan overal in Azië een reis op maat ontwerpen; Way to Asia-reizen zijn inspiratie, geen beperking.',
  hu:'Mondja el az ügynöknek, mi fontos. Személyre szabott útvonalat készíthet Ázsia bármely részére; a Way to Asia utak inspirációt adnak, nem korlátoznak.',
  sv:'Berätta för agenten vad som är viktigt. Den kan skapa en skräddarsydd rutt var som helst i Asien; Way to Asia-resor är inspiration, inte en begränsning.',
  no:'Fortell agenten hva som betyr mest. Den kan lage en skreddersydd rute hvor som helst i Asia; Way to Asia-reiser er inspirasjon, ikke en begrensning.',
};

const routeDetailCopy:Record<Locale,{highlights:string;onward:string;travellers:string;sourceNote:string}>={
  en:{highlights:'Ideas for these days',onward:'Next leg',travellers:'What travellers consistently mention',sourceNote:'Current forum and review signals · Open the sources and judge them for yourself'},
  da:{highlights:'Oplevelser på disse dage',onward:'Videre',travellers:'Det rejsende ofte fremhæver',sourceNote:'Aktuelle signaler fra fora og anmeldelser · Åbn kilderne og vurder dem selv'},
  es:{highlights:'Ideas para estos días',onward:'Siguiente trayecto',travellers:'Lo que suelen señalar los viajeros',sourceNote:'Señales actuales de foros y reseñas · Abre las fuentes y valóralas'},
  it:{highlights:'Idee per questi giorni',onward:'Tappa successiva',travellers:'Ciò che i viaggiatori segnalano spesso',sourceNote:'Segnali attuali da forum e recensioni · Apri le fonti e valutale'},
  fr:{highlights:'Idées pour ces journées',onward:'Étape suivante',travellers:'Ce que les voyageurs mentionnent souvent',sourceNote:'Signaux actuels issus de forums et d’avis · Ouvrez les sources et jugez-les'},
  nl:{highlights:'Ideeën voor deze dagen',onward:'Volgende traject',travellers:'Wat reizigers vaak noemen',sourceNote:'Actuele signalen uit forums en reviews · Open de bronnen en beoordeel ze zelf'},
  hu:{highlights:'Ötletek ezekre a napokra',onward:'Következő szakasz',travellers:'Amit az utazók gyakran említenek',sourceNote:'Aktuális fórum- és értékelési jelzések · Nyissa meg és mérlegelje a forrásokat'},
  sv:{highlights:'Idéer för dessa dagar',onward:'Nästa sträcka',travellers:'Det resenärer ofta lyfter fram',sourceNote:'Aktuella signaler från forum och recensioner · Öppna källorna och bedöm dem själv'},
  no:{highlights:'Ideer for disse dagene',onward:'Neste etappe',travellers:'Det reisende ofte trekker frem',sourceNote:'Aktuelle signaler fra forum og anmeldelser · Åpne kildene og vurder dem selv'},
};

const destinationNames:Record<string,string>={china:'China','south-korea':'South Korea',thailand:'Thailand',vietnam:'Vietnam',indonesia:'Indonesia'};
const interestKeys=['food','history','nature','art','active','wellness','family','celebration'];
const formatMoney=(prices:Record<string,number>,locale:Locale)=>{const currency=locale==='da'?'DKK':locale==='sv'?'SEK':locale==='no'?'NOK':locale==='hu'?'HUF':'EUR';return new Intl.NumberFormat(locale,{style:'currency',currency,maximumFractionDigits:0}).format(prices[currency])};

export default function TripPlanner({locale='en'}:{locale?:Locale}){
  const c:Record<string,string>={...(copy[locale]??copy.en),intro:agentIntro[locale]??agentIntro.en};
  const a=agentCopy[locale]??agentCopy.en;
  const routeCopy=routeDetailCopy[locale]??routeDetailCopy.en;
  const [suggestion,setSuggestion]=useState<TripSuggestion|null>(null);
  const [profile,setProfile]=useState<Record<string,unknown>|null>(null);
  const [status,setStatus]=useState<'idle'|'loading'|'error'>('idle');
  const [error,setError]=useState('');
  const [duration,setDuration]=useState(12);
  const destinations=useMemo(()=>Object.entries(destinationNames),[]);
  async function requestSuggestion(body:Record<string,unknown>){
    const response=await fetch('/api/trip-suggestion',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json() as {suggestion?:TripSuggestion;error?:string;code?:string};if(!response.ok||!result.suggestion)throw new Error(result.code==='AI_DAILY_LIMIT'?a.capacityError:result.error||'Unable to create a suggestion.');setSuggestion(result.suggestion);setStatus('idle');requestAnimationFrame(()=>document.querySelector('[data-trip-result]')?.scrollIntoView({behavior:'smooth',block:'start'}));
  }
  async function submit(event:SyntheticEvent<HTMLFormElement,SubmitEvent>){
    event.preventDefault();const data=new FormData(event.currentTarget);const interests=data.getAll('interests').map(String);const destinationIdeas=String(data.get('destinationIdeas')||'').trim();const notes=String(data.get('notes')||'').trim();if(!interests.length&&!destinationIdeas&&!notes){setError(a.inputError);setStatus('error');return}
    setStatus('loading');setError('');const body={locale,destinations:data.getAll('destinations').map(String),destinationIdeas,travelMonth:String(data.get('travelMonth')||'flexible'),durationDays:duration,adults:Number(data.get('adults')),children:Number(data.get('children')),budget:String(data.get('budget')),pace:String(data.get('pace')),interests,notes};setProfile(body);
    try{await requestSuggestion(body)}catch(reason){setError(reason instanceof Error?reason.message:'Unable to create a suggestion.');setStatus('error')}
  }
  async function refine(event:SyntheticEvent<HTMLFormElement,SubmitEvent>){
    event.preventDefault();if(!profile||!suggestion)return;const form=event.currentTarget;const data=new FormData(form);const refinement=String(data.get('refinement')||'').trim();if(!refinement){setError(a.inputError);setStatus('error');return}setStatus('loading');setError('');
    try{await requestSuggestion({...profile,currentSuggestion:suggestion,refinement});form.reset()}catch(reason){setError(reason instanceof Error?reason.message:'Unable to refine the suggestion.');setStatus('error')}
  }
  if(suggestion)return <article className="trip-result" data-trip-result aria-live="polite"><header><span className="agent-mark">AI · Way to Asia</span><h2>{suggestion.title}</h2><p>{suggestion.summary}</p><div className="result-meta"><span>{suggestion.recommendedDuration}</span><span>{suggestion.matchedJourneys.length?c.notice:a.tailorMade}</span></div></header><div className="result-grid"><section><h3>{c.route}</h3><ol className="route-list">{suggestion.route.map((stop,index)=><li key={`${stop.days}-${index}`}><span>{stop.days}</span><div><b>{stop.place}</b><p>{stop.focus}</p><small>{routeCopy.highlights}</small><ul>{stop.highlights.map(item=><li key={item}>{item}</li>)}</ul>{stop.onwardTravel&&<p className="onward"><strong>{routeCopy.onward}:</strong> {stop.onwardTravel}</p>}</div></li>)}</ol></section><aside><section><h3>{c.fit}</h3><ul>{suggestion.fitReasons.map(item=><li key={item}>{item}</li>)}</ul></section><section><h3>{c.notesTitle}</h3><ul>{suggestion.practicalNotes.map(item=><li key={item}>{item}</li>)}</ul></section></aside></div>{suggestion.travellerInsights.length>0&&<section className="traveller-research"><h3>{routeCopy.travellers}</h3><p>{routeCopy.sourceNote}</p><ul>{suggestion.travellerInsights.map(item=><li key={item.insight}><span>{item.insight}</span><div>{item.sources.map(source=><a key={source.url} href={source.url} target="_blank" rel="noreferrer">{source.title} · {source.domain} ↗</a>)}</div></li>)}</ul></section>}{suggestion.matchedJourneys.length>0&&<section className="matches"><h3>{c.matches}</h3><div>{suggestion.matchedJourneys.map(journey=><a href={journey.href} key={journey.slug}><span>{journey.country.replace('-', ' ')}</span><b>{journey.name}</b><small>{journey.duration} {c.daysLabel} · {c.from} {formatMoney(journey.prices,locale)}</small></a>)}</div></section>}<section className="agent-refinement"><header><span className="agent-mark">AI · Way to Asia</span><h3>{a.refineTitle}</h3><p>{a.refineIntro}</p></header><form onSubmit={refine}><textarea name="refinement" rows={3} maxLength={700} placeholder={a.refinePlaceholder} required/><button className="secondary" type="submit" disabled={status==='loading'}>{status==='loading'?a.refining:a.refineSubmit} ↗</button></form>{error&&<p className="form-error" role="alert">{error}</p>}</section><HbxAvailability locale={locale} preferredCountry={suggestion.matchedJourneys[0]?.country}/><p className="closing">{suggestion.closing}</p><footer><button type="button" className="secondary" onClick={()=>{setSuggestion(null);setProfile(null);setError('')}}>{c.newIdea}</button><a className="btn" href={`/${locale}/contact`}>{c.contact} ↗</a></footer></article>;
  return <form className="trip-planner" onSubmit={submit}><header><span className="agent-mark">AI · Way to Asia</span><h2>{c.start}</h2><p>{c.intro}</p></header><div className="planner-grid"><fieldset className="wide"><legend>{c.where}</legend><label className="choice"><input type="checkbox" name="destinations" value="" defaultChecked/><span>{a.anywhere}</span></label>{destinations.map(([value,label])=><label className="choice" key={value}><input type="checkbox" name="destinations" value={value}/><span>{label}</span></label>)}</fieldset><label className="wide prompt-field">{a.destinationIdeas}<textarea name="destinationIdeas" rows={2} maxLength={180} placeholder={a.destinationPlaceholder}/></label><label>{c.when}<input type="month" name="travelMonth"/></label><label>{c.days}<output>{duration}</output><input type="range" min="5" max="35" value={duration} onChange={event=>setDuration(Number(event.target.value))}/></label><fieldset><legend>{c.travellers}</legend><div className="inline-fields"><label>{c.adults}<input type="number" name="adults" min="1" max="12" defaultValue="2" required/></label><label>{c.children}<input type="number" name="children" min="0" max="8" defaultValue="0" required/></label></div></fieldset><label>{c.budget}<select name="budget" defaultValue="comfort"><option value="value">{c.value}</option><option value="comfort">{c.comfort}</option><option value="premium">{c.premium}</option><option value="luxury">{c.luxury}</option><option value="unsure">{c.unsure}</option></select></label><label>{c.pace}<select name="pace" defaultValue="balanced"><option value="slow">{c.slow}</option><option value="balanced">{c.balanced}</option><option value="active">{c.active}</option></select></label><fieldset className="wide"><legend>{c.interests}</legend>{interestKeys.map(key=><label className="choice" key={key}><input type="checkbox" name="interests" value={key}/><span>{c[key]}</span></label>)}</fieldset><label className="wide prompt-field">{c.notes}<textarea name="notes" rows={4} maxLength={1000} placeholder={c.placeholder}/></label></div><div className="planner-submit"><p>{c.notice}</p><button className="btn" type="submit" disabled={status==='loading'}>{status==='loading'?c.working:c.submit} ↗</button></div>{error&&<p className="form-error" role="alert">{error}</p>}</form>;
}
