export const locales = ['en','es','it','fr','nl','hu','sv','da','no'] as const;
export type Locale = typeof locales[number];
export const defaultLocale: Locale = 'en';
export const localeNames: Record<Locale,string> = {en:'English',es:'Español',it:'Italiano',fr:'Français',nl:'Nederlands',hu:'Magyar',sv:'Svenska',da:'Dansk',no:'Norsk'};
export const messages: Record<Locale, Record<string,string>> = {
 en:{navDestinations:'Destinations',navTours:'Journeys',navAbout:'Our studio',navContact:'Start planning',heroEyebrow:'Private journeys · Small groups',heroTitle:'Asia, composed around you.',heroBody:'Thoughtful journeys shaped by local knowledge, unhurried days and the freedom to follow your curiosity.',explore:'Explore the journey',destinations:'Five worlds. One considered route.',featured:'The flagship journey',trust:'Travel slowly. See deeply.',newsletter:'Notes from the road',email:'Email address',submit:'Send me inspiration',tours:'Journeys',things:'Ways to experience',gallery:'Field notes',inquire:'Request a private proposal',from:'From',days:'days',all:'All destinations',aboutTitle:'We design journeys, not packages.',contactTitle:'Tell us where Asia begins for you.'},
 es:{navDestinations:'Destinos',navTours:'Viajes',navAbout:'Nuestro estudio',navContact:'Planificar',heroEyebrow:'Viajes privados · Grupos pequeños',heroTitle:'Asia, creada a tu medida.',heroBody:'Viajes atentos, conocimiento local y tiempo para seguir tu curiosidad.',explore:'Explorar el viaje'},
 it:{navDestinations:'Destinazioni',navTours:'Viaggi',navAbout:'Il nostro studio',navContact:'Inizia a pianificare',heroEyebrow:'Viaggi privati · Piccoli gruppi',heroTitle:'L’Asia, composta intorno a te.',heroBody:'Viaggi curati con conoscenza locale e il tempo di seguire la curiosità.',explore:'Esplora il viaggio'},
 fr:{navDestinations:'Destinations',navTours:'Voyages',navAbout:'Notre studio',navContact:'Commencer',heroEyebrow:'Voyages privés · Petits groupes',heroTitle:'L’Asie, composée autour de vous.',heroBody:'Des voyages réfléchis, une connaissance locale et le temps de suivre votre curiosité.',explore:'Explorer le voyage'},
 nl:{navDestinations:'Bestemmingen',navTours:'Reizen',navAbout:'Onze studio',navContact:'Begin met plannen',heroEyebrow:'Privéreizen · Kleine groepen',heroTitle:'Azië, rond jou gecomponeerd.',heroBody:'Doordachte reizen met lokale kennis en ruimte voor nieuwsgierigheid.',explore:'Ontdek de reis'},
 hu:{navDestinations:'Úti célok',navTours:'Utazások',navAbout:'Stúdiónk',navContact:'Tervezés',heroEyebrow:'Privát utak · Kis csoportok',heroTitle:'Ázsia, Ön köré komponálva.',heroBody:'Átgondolt utazások helyi tudással és idővel a felfedezésre.',explore:'Fedezze fel az utat'},
 sv:{navDestinations:'Resmål',navTours:'Resor',navAbout:'Vår studio',navContact:'Börja planera',heroEyebrow:'Privata resor · Små grupper',heroTitle:'Asien, komponerat kring dig.',heroBody:'Genomtänkta resor med lokal kunskap och tid för nyfikenhet.',explore:'Utforska resan'},
 da:{navDestinations:'Destinationer',navTours:'Rejser',navAbout:'Vores studio',navContact:'Start planlægning',heroEyebrow:'Private rejser · Små grupper',heroTitle:'Asien, komponeret omkring dig.',heroBody:'Gennemtænkte rejser med lokal indsigt og tid til at følge nysgerrigheden.',explore:'Udforsk rejsen'},
 no:{navDestinations:'Reisemål',navTours:'Reiser',navAbout:'Vårt studio',navContact:'Start planlegging',heroEyebrow:'Private reiser · Små grupper',heroTitle:'Asia, komponert rundt deg.',heroBody:'Gjennomtenkte reiser med lokal kunnskap og tid til nysgjerrighet.',explore:'Utforsk reisen'}
};
const fallback = messages.en;
export function t(locale:Locale,key:string){return messages[locale][key] ?? fallback[key] ?? key}
export function localizedPath(locale:Locale,path=''){return `/${locale}${path === '/' ? '' : path}`}
